# -*- coding: utf-8 -*-
import re, collections

MAP2 = {
    'paar': '幾個', 'Schwester': '姐姐', 'dabei': '其中', 'unglaublich': '難以置信的',
    'wenig': '一點', 'Ist': '是', 'antwortete': '回答道', 'habt': '有',
    'erinnerte': '讓人想起', 'egal': '無所謂', 'zwar': '雖然', 'Alexias': '亞莉西亞的',
    'gemacht': '做了', 'unsere': '我們的', 'unserer': '我們的', 'unseren': '我們的',
    'gute': '好的', 'guten': '好的', 'guter': '好的', 'gutes': '好的',
    'klar': '清楚', 'gerne': '樂意', 'los': '出發', 'kurz': '短暫地',
    'gesagt': '說過', 'glaube': '相信', 'erzählt': '講述了',
    'möchte': '想要', 'Ordens': '騎士團的',
    'all': '所有', 'recht': '對',
    'seufzte': '嘆了口氣', 'Blick': '目光', 'Vielleicht': '也許',
    'Menschen': '人們', 'passiert': '發生了', 'eben': '就是',
    'angemeldet': '報名了', 'schneller': '更快',
    'D-Das': '這', 'komplett': '完全', 'Keine': '沒有',
    'wichtig': '重要', 'erzählen': '講述',
    'stimmt': '沒錯', 'ganzen': '整個', 'Eure': '您的',
    'Arbeit': '工作', 'solltest': '應該', 'Tages': '天的',
    'schaffen': '做到', 'Diese': '這些', 'sicher': '確信',
    'ebenfalls': '同樣', 'betrachtete': '端詳著',
    'Ritterorden': '騎士團', 'Teil': '部分',
    'na': '嗯', 'könnt': '能', 'warst': '曾是',
    'hin': '去', 'Weile': '一會兒', 'namens': '名為',
    'ersten': '第一批', 'gibt': '有', 'machen': '做',
    'unterbrach': '打斷了', 'irgendeinem': '某個', 'irgendeiner': '某個',
    'Grund': '原因', 'bitte': '請',
    'betraten': '走進了', 'weitere': '更多的',
    'knieten': '跪著', 'klug': '聰明的',
    'fand': '覺得', 'spielt': '起', 'damals': '當時',
    'entlang': '沿著', 'wischte': '擦了',
    'fühlte': '感覺到', 'hob': '舉起了',
    'zitterte': '顫抖著', 'hergeführt': '帶來的',
    'fragen': '問', 'denen': '那些',
    'gekommen': '來的', 'schwer': '困難的',
    'steckte': '放進了', 'zeigte': '指了',
    'eineinhalb': '一百五十萬', 'viele': '許多',
    'Mal': '次', 'dies': '此事',
    'Dieser': '這個', 'schien': '似乎',
    'Gammas': '伽瑪的', 'verstehe': '明白了',
    'geht': '去吧', 'Sein': '他的',
    'niemals': '永遠不', 'erzählte': '講述了',
    'einziger': '唯一的', 'leben': '活著',
    'anerkannt': '認可的', 'vermochte': '能夠',
    'erst': '才', 'Nun': '那麼',
    'Tut': '抱', 'leid': '歉',
    'liefen': '跑著', 'zulassen': '允許',
    'blieben': '停下了', 'spritzte': '濺出了',
    'sagst': '說', 'bewunderte': '崇拜著',
    'nächsten': '下一個', 'eins': '一',
    'Zwei': '兩', 'befand': '處於',
    'befreit': '解放了', 'sinnlosen': '無意義的',
    'Wahl': '選擇', 'Bushin-Festival': '武神祭',
    'Träum': '做夢吧', 'herbei': '前來',
    'teilzunehmen': '參加', 'teilnehmen': '參加',
    'interessiert': '感興趣', 'Agh': '啊',
    'außer': '除了', 'Sag': '說',
    'getroffen': '擊中了', 'weißt': '知道',
    'abmelden': '退出報名', 'Ahnung': '頭緒',
    'betrat': '走進了', 'irgendetwas': '什麼東西',
    'ansehen': '看出', 'teilte': '共用著',
    'Midgar-Gelehrtenakademie': '密德迦爾學者學院',
    'wandte': '轉過了', 'niemandem': '任何人',
    'Leute': '人', 'letzter': '最近',
    'darum': '為此', 'gebeten': '請求了',
    'seid': '是', 'bitten': '請求',
    'anderer': '其他的', 'ruhig': '安靜地',
    'nennen': '稱呼', 'erwiderte': '回道',
    "Iris'": '艾莉絲的', 'Hab': '要有',
    'scheint': '似乎是', 'gefunden': '找到了',
    'tun': '做', 'wahrscheinlich': '大概',
    'beschützen': '保護', 'Lutherans': '路德蘭的',
    'Dieses': '這個', 'stellten': '排了',
    'riesige': '巨大的', 'riesiger': '巨大的', 'riesigen': '巨大的',
    'allein': '獨自', 'gegründet': '成立了',
    'wahr': '真的', 'richtig': '對吧',
    'schenkt': '給予', 'Überlasst': '交給',
    'Untersuchungen': '調查', 'macht': '做',
    'genug': '足夠', 'murmelte': '嘟囔著',
    'Feinde': '敵人', 'sahen': '看著',
    'Danke': '謝謝', 'lächelnd': '微笑著',
    'Vielen': '非常', 'Dank': '感謝',
    'fest': '確定了', 'lieben': '喜歡',
    'wagt': '敢', 'komm': '過來',
    'Mitsugoshi-Kaufhaus': '三越百貨',
    'kürzlich': '最近', 'eröffnet': '開業了',
    'angeblich': '據說', 'klatschte': '拍了',
    'funkelten': '閃耀著',

    'Hey': '嘿', 'Oh': '哦', 'Hm': '嗯', 'Nee': '沒有',
    'Hehehe': '嘿嘿嘿', 'Hach': '唉',
    'Kopf': '頭', 'gewinne': '贏', 'verliere': '輸',
    'Nein': '不', 'brandneue': '全新的', 'selber': '自己',
    'essen': '吃', 'schenken': '送',
    'stolz': '驕傲地', 'geht': '去吧',
    'Bohne': '一點兒',
    'voller': '滿是', 'Geschäfte': '商店',
    'Lagen': '地段', 'überfüllt': '擁擠的',
    'beliebtesten': '最受歡迎的', 'besagtes': '說的那家',
    'fertig': '完蛋', 'tätschelte': '拍了拍',
    'Hüfte': '腰', 'angeblich': '據說',
    'zieht': '出沒', 'getötet': '殺死了',
    'Flüsterton': '低聲', 'Wow': '哇',
    'rausgehen': '出門', 'spaßig': '有趣的',
    'stellen': '排隊', 'Sonst': '否則',
    'scheuchte': '催促著',
    'baggerte': '搭訕了', 'Schild': '牌子',
    'hundertfach': '百倍', 'kampferprobten': '身經百戰的',
    'höflichen': '禮貌的', 'abserviert': '打發了',
    'Entschuldigen': '不好意思',
    'dunkelbraunes': '深棕色的', 'dunkelbraunen': '深棕色的',
    'braune': '棕色的', 'braunen': '棕色的',
    'Gesichtsausdruck': '表情', 'wirkte': '顯得',
    'elegant': '優雅的', 'elegante': '優雅的', 'eleganten': '優雅的',
    'simplen': '簡約的', 'einteiligen': '連身的', 'einteiligen': '連身的',
    'Logo': '標誌', 'Handelshauses': '商社的',
    'Flugbegleiterin': '空姐',
    'früheren': '以前的',
    'Zeigefinger': '食指', 'deutete': '指向',
    'Fragebogen': '問卷',
    'Person': '人', 'reicht': '夠了', 'völlig': '完全',
    'blickte': '望著', 'zurück': '回去',
    'verzweifelt': '絕望地', 'hinterhersahen': '望著我走遠',
    'luxuriösen': '豪華的', 'luxuriösen': '豪華的',
    'oberflächlich': '表面的', 'glamourös': '華麗的',
    'stimmte': '和諧的', 'kleinste': '最小的',
    'schuf': '營造了', 'entspannte': '輕鬆的',
    'ungeschulten': '外行的', 'Auge': '眼光',
    'geschmackvolle': '有品味的', 'moderne': '現代的',
    'Produkte': '產品', 'Gesicht': '臉',
    'berühmten': '著名的', 'diversen': '各種',
    'lauter': '許多', 'Dinge': '東西',
    'verfeinerten': '精緻的', 'erhältlich': '有售的',
    'nachvollziehen': '理解', 'beliebt': '受歡迎的',
    'erstaunlich': '驚人的', 'erstaunlichen': '驚人的',
    'breiten': '寬闘的',
    'glänzenden': '閃亮的', 'glänzender': '閃亮的',
    'geschnitzten': '雕刻的',
    'langsam': '慢慢地', 'öffneten': '打開了',
    'erstreckte': '延伸著',
    'griechischen': '希臘的',
    'hinteren': '後方的',
    'säumten': '排列在', 'Seiten': '兩側',
    'nieder': '下',
    'filigranen': '精緻的',
    'glich': '像', 'ergoss': '傾瀉',
    'darauf': '上面', 'niemand': '沒有人',
    'indigoblauem': '靛藍色的',
    'bezaubernden': '迷人的',
    'leicht': '容易', 'kluges': '聰明的',
    'scharfsinnigen': '敏銳的', 'scharfsinnige': '敏銳的',
    'blauen': '藍色的', 'blaue': '藍色的',
    'intelligente': '聰明的',
    'überaus': '極其',
    'entscheidende': '致命的', 'Schwäche': '弱點',
    'nannten': '稱呼',
    'älteste': '最年長的', 'älterer': '年長的',
    'Weitem': '遠',
    'schwächste': '最弱的',
    'ersten': '最初的',
    'Mitglieder': '成員',
    'genannt': '取名為',
    'cool': '酷', 'klingt': '聽起來',
    'besaß': '擁有', 'Einzige': '唯一的', 'Einzigen': '唯一的',
    'weder': '既不', 'Talent': '天賦',
    'Sport': '運動', 'Kämpfen': '戰鬥',
    'Stärkste': '最強的', 'Persönlich': '個人來說',
    'ähnlich': '相似的',
    'wüssten': '知道的話', 'freuen': '高興',
    'wütend': '憤怒地', 'enttäuscht': '失望地',
    'gelernt': '學到了', 'beibringen': '教',
    'Erstens': '第一', 'zweitens': '第二',
    'Rolle': '作用', 'totaler': '完全的',
    'Funken': '一絲',
    'besitzt': '擁有',
    'denselben': '相同的', 'Rat': '建議',
    'Benutze': '使用',
    'verlangte': '要求',
    'körperliche': '身體的',
    'baute': '建立在', 'hasste': '討厭的',
    'widerlegt': '反駁了',
    'zurückdachte': '回想到',
    'aufhören': '停止', 'nachzudenken': '思考',
    'Vergiss': '忘了吧',
    'Models': '模特兒的',
    'scharfe': '清脆的', 'scharfen': '銳利的',
    'Absätze': '高跟',
    'hielt': '按住了',
    'eilte': '趕來了',
    'tauschte': '換了',
    'niedrigeren': '更低的',
    'geschehen': '發生過',
    'umzugehen': '對待',
    'aufziehen': '取笑',
    'anmerken': '指出',
    'blutet': '在流血',
    'Scham': '羞恥', 'glühte': '通紅',
    'verändert': '改變',
    'führen': '帶領', 'setzte': '坐了',
    'schlecht': '差',
    'hereinflutete': '流洩進來',
    'König': '國王',
    'vorzubereiten': '準備',
    'berührt': '感動',
    'übereinander': '交叉著',
    'stützte': '撐著',
    'sammelte': '聚集了',
    'blauviolette': '藍紫色的',
    'fliegen': '飛',
    'schoss': '射向',
    'teilte': '分成了',
    'Abermillionen': '無數',
    'strömte': '流淌著',
    'lindern': '緩解',
    'verbessern': '改善',
    'heilen': '治癒',
    'bebender': '顫抖的',
    'niederkniete': '跪下了',
    'vergossen': '流下了',
    'schniefte': '抽泣著', 'weinte': '哭了',
    'aufgepasst': '學得好',
    'vorhin': '剛才',
    'drehte': '怎麼看都', 'wendete': '都',
    'beantworte': '回答',
    'interessiert': '感興趣的',
    'verprügelt': '揍了',
    'nahe': '快要',
    'gebeten': '請求了',
    'diversen': '各種的',
    'ausgegeben': '說成',
    'minderen': '微薄的',
    'bemüht': '努力了',
    'wenigstens': '至少',
    'göttlichen': '神聖的',
    'geteilt': '分享的',
    'Bahnhof': '一頭霧水',
    'vermischt': '混合',
    'aushärten': '硬化',
    'anfangen': '做到',
    'umsonst': '白白地',
    'belass': '就這樣吧',
    'unbedingt': '一定',
    'kapier': '懂了',
    'ausgeschlossen': '排除在外',
    'einzubeziehen': '納入',
    'verdient': '賺到',
    'Derzeit': '目前', 'verläuft': '進展',
    'größeren': '較大的',
    'ungestört': '不受干擾地',
    'bewegen': '活動',
    'unnötig': '多餘的',
    'benutzten': '利用了',
    'massig': '大量的',
    'scheffeln': '撈錢',
    'links': '旁邊',
    'liegen': '晾著',
    'abgegeben': '分給',
    'rumkriecht': '爬來爬去',
    'gebaut': '建造了',
    'reichen': '夠了',
    'klitzekleines': '一丁點兒',
    'bisschen': '一點',
    'gefragt': '想問',
    'leihen': '借', 'zurückzahlen': '還錢',
    'vorbereiten': '準備',
    'Anweisungen': '指示',
    'geschoben': '推進了',
    'ganzer': '整整一座',
    'schier': '簡直', 'unübersichtliche': '數不清的',
    'glitzernder': '閃閃發光的',
    'Nein': '不',
    'unterbrach': '打斷了',
    'griff': '伸手',
    'Münzen': '硬幣',
    'übertrieben': '誇張地',
    'fielen': '掉落了', 'klirrend': '叮噹作響地',
    'gesamte': '全部的',
    'Aufmerksamkeit': '注意力',
    'lenken': '集中到',
    'höchster': '最高的', 'Vorsicht': '小心',
    'Konzentration': '專注',
    'ergriff': '抓起了',
    'fünfzehn': '十五',
    'herum': '展示一圈',
    'eineinhalb': '一百五十萬',
    'geblickt': '看著',
    'flink': '敏捷地',
    'genauso': '一樣',
    'geschnappt': '偷拿了',
    'aufgefallen': '發覺',
    'Lage': '能力',
    'Ahnung': '頭緒', 'ironisch': '諷刺的',
    'Sorge': '擔心', 'unterdrückte': '忍住了',
    'Lachen': '笑',
    'beiseite': '放回去',
    'Anschließend': '接著',
    'kniete': '跪下了',
    'besucht': '來訪',
    'verzeiht': '請原諒',
    'mitten': '正在', 'herausgefunden': '查明',
    'Morden': '謀殺案', 'steckt': '幕後主使',
    'Geduld': '耐心', 'verspreche': '保證',
    'höchstpersönlich': '親自', 'erledigen': '解決',
    'erledigt': '完蛋了',
    'Vergangenheit': '過去',
    'verrottender': '腐爛的',
    'verendet': '死去',
    'verlassen': '拋棄', 'gezwungen': '被迫',
    'fliehen': '逃離', 'verloren': '失去了一切',
    'Tiefen': '深處', 'Schmerzes': '痛苦的',
    'Angst': '恐懼', 'Verzweiflung': '絕望',
    'gefangen': '困在',
    'gerettet': '拯救了',
    'erfüllt': '充滿',
    'einst': '曾經',
    'zustimmen': '同意',
    'begründen': '解釋',
    'instinktiv': '本能地',
    'oberflächliche': '表面的',
    'Inneren': '內心深處',
    'berührte': '觸碰了',
    'Fesseln': '束縛',
    'erlöst': '解放了',
    'Unterdrücktes': '被壓抑的',
    'befreit': '釋放了',
    'wiedergefunden': '找回了',
    'wiedergeboren': '重生了',
    'widmen': '奉獻給',
    'wider': '違背',
    'starken': '強烈的',
    'überholt': '超越了',
    'kroch': '爬著',
    'gedemütigt': '被羞辱了',
    'Irgendwann': '終有一天',
    'anstrengte': '努力',
    'Worin': '什麼', 'bestand': '在於',
    'Anstatt': '與其',
    'weiterhin': '繼續',
    'schämen': '丟臉',
    'verschwinden': '消失',
    'entschlossen': '決定',
    'aus': '從',
    'Weisheiten': '智慧',
    'erkannte': '認清了',
    'verzweifelt': '絕望的',
    'stürzte': '撲向了',
    'riskierte': '賭上了',
    'buchstäblich': '字面上地',
    'rekreieren': '重現',
    'Nachhinein': '事後',
    'durchschaut': '看穿了',
    'Leid': '痛苦',
    'ebenso': '同樣地',
    'realisierte': '意識到',
    'verspürte': '感受到',
    'Trauer': '悲傷',
    'Punkt': '境界',
    'erreichen': '達到',
    'Brauchte': '需要嗎',
    'nachdachte': '思考',
    'weinen': '哭泣',
    'stärker': '更強大',
    'größer': '更大',
    'erschaffen': '創造',
    'würdig': '配得上的',
    'holte': '把...拉回了',
    'Realität': '現實',
    'Idee': '想法',
    'nachgehen': '追查',
    'klammes': '沉重的',
    'spielerischer': '輕鬆的', 'Leichtigkeit': '輕鬆',
    'Hinweise': '線索',
    'aufgeben': '放棄',
    'Dreizehn': '十三', 'dreizehn': '十三',
    'Nummer': '號',
    'blinzelte': '眨了眨眼',
    'scharfen': '銳利的',
    'Verbindungsperson': '聯絡人',
    'sonstige': '其他的', 'Aufgaben': '任務',
    'einsetzen': '使用',
    'Ehre': '榮幸',
    'Nervosität': '緊張',
    'rufen': '叫',
    'sobald': '一旦',
    'Nutzen': '用處',
    'senkte': '低下了',
    'Kopf': '頭',
    'zurückzukehren': '回去了',
    'billigste': '最便宜的',
    'hochwertigste': '最高級的',
    'Bereitet': '準備',
    'kostet': '花多少',
    'hundert': '一百', 'Prozent': '百分比',
    'billiger': '更便宜',
    'umsonst': '免費的',
    'Glückspilz': '幸運兒',
    'hätte': '想要', 'Stück': '份',
    'verwandelte': '變回了',
    'lächelte': '微笑了',
    'spät': '遲', 'dran': '來不及',
    'ordentlich': '好好地', 'gelassen': '花時間',
    'besorgt': '買到了',
    'Rücken': '背後',
    'unschuldig': '無辜', 'ganz': '完全',
    'pausenlos': '不停地', 'ausgefragt': '追問',
    'geheißen': '叫什麼',
    'Naja': '算了', 'langweiligen': '無聊的',
    'abspeisen': '打發',
    'wichtiger': '更重要的',
    'gedacht': '想到',
    'überzeugt': '確信',
    'müsste': '一定是',
    'dazu': '因此', 'getrieben': '驅使',
    'weibliche': '女人的',
    'schlimmste': '最糟糕的',
    'vorschreiben': '規定',
    'benutzen': '使用',
    'anderes': '另一回事',
    'Geräusch': '聲音',
    'erkennen': '辨認',
    'vernahm': '聽到了', 'deutlich': '清楚地',
    'aufeinanderprallten': '碰撞著',
    'Ferne': '遠處',
    'Stelle': '原地',
    'stehen': '站著',
    'Klo': '廁所',
    'verdutzt': '愣住了',
    'Ernst': '認真的',
    'Unglück': '災難',
    'Würde': '尊嚴',
    'Tonfall': '語氣',
    'überraschend': '出乎意料地',
    'ernst': '嚴肅的',
    'Geheimnis': '秘密',
    'aufgehoben': '保管好的',
    'Entscheidung': '決定',
    'Abmarsch': '出發',
    'verschwunden': '消失了',
    'machte': '出發了',
    'Richtung': '方向',
    'Kampfgeräusche': '戰鬥聲',
    'folgte': '跟著',
    'Uniform': '制服',
    'kurzen': '短',
    'unverkennbar': '無疑是',
    'gekleideter': '穿著的', 'gekleideter': '穿著的', 'gekleidet': '穿著',
    'Maske': '面具',
    'komisch': '奇怪',
    'vorgab': '假裝',
    'gehören': '屬於',
    'andersherum': '相反',
    'Anwesenheit': '存在',
    'verbergen': '隱藏',
    'kletterte': '爬上了',
    'beobachten': '觀察',
    'aufgeben': '放棄',
    'besiegen': '打敗',
    'Gunsten': '優勢',
    'Fortschritte': '進步',
    'auszurichten': '抵擋',
    'Treffer': '攻擊',
    'entschieden': '決定',
    'tötet': '殺害',
    'unschuldige': '無辜的',
    'befohlen': '命令的',
    'wiederholte': '重複了',
    'weiteres': '又一',
    'Zweifel': '懷疑',
    'Gedanken': '心裡',
    'Schutz': '保護',
    'logische': '合理的',
    'empfunden': '感受',
    'Bewunderung': '崇拜',
    'nachvollziehen': '理解',
    'begonnen': '開始',
    'imitiert': '模仿', 'imitierte': '模仿了',
    'Anime': '動漫', 'Manga': '漫畫',
    'brannte': '燃燒著',
    'glücklich': '開心的',
    'eingeschlagen': '走上了',
    'Partei': '第三方',
    'durfte': '可以',
    'missbrauchte': '濫用',
    'Naivität': '天真',
    'Kompromisse': '妥協',
    'schlug': '打掉了',
    'spürte': '感覺到了',
    'Präsenz': '氣息',
    'zukommen': '接近',
    'Schlag': '攻擊',
    'auswich': '閃開了',
    'blockte': '擋住了',
    'trat': '踢了',
    'Abstand': '距離',
    'unregelmäßige': '不規則的',
    'Kontrolle': '控制',
    'Widersacher': '對手',
    'sonderlich': '特別',
    'problemlos': '毫無問題地',
    'dritt': '三個人',
    'armes': '可憐的',
    'grausam': '殘忍',
    'schinden': '拖延',
    'fairer': '公平的',
    'umzingelten': '包圍了',
    'positionierte': '調整位置',
    'freizuhalten': '空出來',
    'abzuhalten': '阻止',
    'gelangen': '繞到',
    'abzudecken': '防禦',
    'durchbohrte': '刺穿了',
    'dumpfer': '沉悶的',
    'Stiefel': '靴子',
    'grub': '踹進了',
    'Knacken': '咔嚓', 'Brechen': '斷裂',
    'spuckte': '吐出了',
    'schwang': '揮向了',
    'wich': '閃開了',
    'Reichweite': '攻擊範圍',
    'blutige': '血淋淋的',
    'hereingefallen': '上當了',
    'aufmerksam': '警覺的',
    'getreten': '踢了',
    'ausholen': '再次揮劍',
    'anzustarren': '瞪著',
    'funkelten': '閃爍著',
    'Mondlicht': '月光',
    'direkt': '就在',
    'Erwischt': '上當了',
    'verschwendete': '浪費',
    'leuchtende': '發光的',
    'schnellte': '飛向了',
    'abgewandt': '移開了',
    'Stirb': '去死吧',
    'durch': '穿過了',
    'frisches': '鮮',
    'umher': '四處',
    'tief': '深',
    'landen': '擊中',
    'schlechter': '更糟',
    'zuvor': '之前',
    'verwundet': '受傷的',
    'schwingen': '揮動',
    'ignorieren': '忽視',
    'gebrochene': '斷了的',
    'gebohrt': '刺穿了',
    'sterben': '死',
    'verabscheute': '厭惡',
    'verlassen': '依賴',
    'getötet': '被殺',
    'versicherte': '不斷告訴自己',
    'schlucken': '吞下',
    'Himmel': '天空',
    'herab': '而下',
    'glitt': '滑翔',
    'lautlos': '無聲地',
    'landete': '落地了',
    'schlitzte': '劈成了',
    'Hälften': '兩半',
    'erzeugte': '噴出了',
    'Gestank': '惡臭',
    'erfüllte': '瀰漫了',
    'befreite': '甩掉了',
    'zeichnete': '劃出了', 'Linie': '一條線',
    'besudeln': '玷汙',
    'mächtigste': '最強大的',
    'Perfektion': '完美',
    'gezeigt': '展示了',
    'bezahlen': '性命償還',
    'gesprochen': '開口',
    'bewegten': '動了',
    'sprangen': '跳離了',
    'kletterten': '攀爬著', 'empor': '向上',
    'erreichten': '到達了',
    'verfolgte': '追了上去',
    'Warte': '等等',
    'stoppte': '讓...停下了',
    'bloß': '到底',
    'zitterte': '顫抖著',
    'wortlos': '沉默地',
    'augenblicklich': '立刻',
    'benutzt': '使用', 'Gegen': '對抗',
    'Freund': '朋友',
    'abwandte': '背過身去',
    'einmischen': '插手', 'Misch': '別',
    'schöneres': '更美好的',
    'unterbrach': '打斷了',
    'Blutdurst': '殺意',
    'überwältigte': '壓倒了',
    'Angesicht': '面前',
    'zwangen': '迫使',
    'Instinkte': '本能',
    'beizugeben': '屈服',
    'widersetzen': '反抗',
    'Sicherheit': '肯定',
    'flatterte': '飄動著',
    'Schwertkunst': '劍術',
    'verschwand': '消失在了',
    'Nacht': '夜色',
    'menschenleere': '空無一人的',
    'vollkommen': '完全',
    'allein': '獨自一人',
    'Seite': '側腹',
    'zitternden': '顫抖的',
    'Dummes': '愚蠢的事',
    'verstanden': '明白了',
    'unersetzlich': '不可替代的',
    'nämlich': '也就是',
    'schwand': '漸漸消失',
    'Bewusstsein': '意識',
    'dunklen': '黑暗的',
    'hochzuziehen': '撐起來',
    'woraufhin': '然後',
    'entfernte': '遙遠的',
    'Schritte': '腳步聲', 'näherten': '靠近了',
    'zusammenbrach': '倒下',
    'Weiches': '柔軟的東西',
    'auffing': '接住了',
    'schmiegte': '依偎著',
    'gefasst': '有心理準備',
    'verstreut': '散落著',
    'Kampf': '戰鬥',
    'beschloss': '決定了',
    'entkommen': '逃跑',
    'gehüllt': '籠罩著',
    'vergewisserten': '確認了',
    'gefolgt': '跟蹤',
    'eilig': '匆忙',
    'stützten': '撐著',
    'keuchten': '喘著氣',
    'Atem': '呼吸聲',
    'ertönte': '響了',
    'dorthin': '那邊',
    'näherte': '接近了',
    'zogen': '拔出了',
    'bereit': '準備好了',
    'bohrte': '刺穿了',
    'Schädel': '頭骨',
    'jegliche': '任何',
    'gespießt': '貫穿了',
    'gezogen': '拔出了',
    'Richtungen': '方向',
    'letzten': '最後的',
    'zusammen': '倒下了',
    'tauchte': '出現了',
    'langen': '長長的',
    'verborgen': '隱藏著',
    'Magier': '魔法師',
    'Musstet': '讓你們',
    'warten': '等待',
    'stamme': '來自',
    'tiefsten': '最深的',
    'nackter': '赤裸的',
    'entkommen': '逃走',
    'rannte': '跑了',
    'bereits': '已經',
    'Wundervoll': '精彩',
    'eingeholt': '追上了',
    'beeindruckt': '佩服',
    'Überlasst': '交給',
    'nötigen': '必要的',
    'Informationen': '情報',
    'herausbekommen': '查出來',
    'Fehler': '錯誤',
    'gesenktem': '低著的', 'Haupt': '頭',
    'Schönheit': '美女',
    'bewaffnet': '武裝的',
    'unbewaffnet': '手無寸鐵的',
    'Absatzschuhe': '高跟鞋',
    'entschied': '決定了',
    'flinken': '迅速的',
    'schutzlose': '毫無防備的',
    'beseitigen': '消滅',
    'Plan': '計劃',
    'Flattern': '飛揚',
    'Kleids': '洋裝的', 'Kleides': '洋裝的',
    'blassen': '蒼白的',
    'schnitt': '切過了',
    'verspätet': '遲了一步',
    'auszustrecken': '伸出',
    'Daumen': '拇指',
    'ragte': '露出了',
    'Absatz': '鞋跟',
    'Schuhs': '鞋子的',
    'strömte': '湧出了',
    'verteilte': '蔓延在',
    'gnädig': '仁慈的',
    'eisiger': '冰冷的', 'scharfer': '銳利的',
    'schnellen': '快速的',
    'Saum': '裙擺',
    'weißes': '白皙的',
    'entstellte': '面目全非的',
    'Bauch': '肚子',
    'geschrieben': '寫著',
    'Narren': '蠢貨的',
    'frisch': '剛', 'gemachten': '整理好的',
    'ernste': '嚴肅的',
    'ausgegeben': '冒充', 'Gruppe': '團體',
    'zumindest': '至少',
    'grübelte': '沉思著',
    'gesenktem': '低垂的',
    'gleichzeitigen': '同時的', 'Angriffe': '襲擊',
    'begegnet': '遇到了',
    'starken': '強大的', 'Schwertkämpferin': '女劍士',
    'nickte': '點了點頭',
    'zusammentragen': '彙整',
    'extrem': '極高的',
    'verfügt': '擁有',
    'feindlich': '敵對', 'gesinnt': '的態度',
    'Spur': '線索',
    'religiöse': '宗教', 'Dämon': '惡魔', 'Diabolos': '迪亞波洛斯',
    'glaubt': '信仰的',
    'tiefer': '更深',
    'reichen': '複雜',
    'Brandstiftung': '縱火',
    'Gelder': '資金', 'genehmigt': '批准',
    'privat': '私人', 'finanzieren': '資助',
    'Augenbrauen': '眉毛',
    'zivile': '文職', 'Stellen': '部門',
    'infiltriert': '滲透了',
    'Spitzel': '間諜', 'Kult': '教團',
    'bestochen': '收買',
    'spontan': '倉促地',
    'widersetzen': '反對',
    'Solange': '只要',
    'umklammerte': '緊握著',
    'Laken': '床單',
    'eigenen': '親', 'Augen': '眼睛',
    'aufleuchten': '發光',
    'Schluss': '結論',
    'Kontrolle': '控制', 'geratenes': '失控的',
    'gehandelt': '是……',
    'gesehen': '見過',
    'Macht': '力量', 'entfesseln': '釋放',
    'eingesperrt': '被關起來',
    'Gedächtnis': '記憶', 'verschwommen': '模糊的',
    'Drogen': '藥物', 'halluziniert': '產生幻覺',
    'lügst': '說謊',
    'klarem': '清醒的',
    'Verstand': '理智',
    'ergriff': '握住了',
    'weglaufen': '逃跑',
    'beschützen': '保護',
    'strich': '撫摸著',
    'Haar': '頭髮',
    'gesund': '健康',
    'helfen': '幫忙',
    'suspendiert': '停職了',
    'Wieso': '為什麼',
    'Beweismitteldiebstahl': '偷竊證物',
    'roten': '紅色的',
    'verschlug': '說不出',
    'Sprache': '話',
    'getan': '做過的事',
    'Knall': '砰一聲',
    'schloss': '關上了',
}

with open('page6.html', 'r', encoding='utf-8') as f:
    html = f.read()

import re
def replace_unknown(m):
    word = m.group(1)
    if word in MAP2:
        zh = MAP2[word]
        return f'<span class="d">{word}<span class="t">{zh}</span></span>'
    return m.group(0)

html = re.sub(
    r'<span class="d">([^<]+)<span class="t">（德）</span></span>',
    replace_unknown,
    html
)

d_count = len(re.findall(r'<span class="d">', html))
c_count = len(re.findall(r'<span class="c">', html))
unknown = len(re.findall(r'（德）', html))

with open('page6.html', 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✅ 第二輪翻譯修補完成')
print(f'   德文詞 (.d): {d_count}')
print(f'   中文互動詞 (.c): {c_count}')
if d_count + c_count > 0:
    print(f'   德文佔比: {d_count/(d_count+c_count)*100:.1f}%')
print(f'   仍需手動翻譯: {unknown}')

if unknown > 0:
    remaining = re.findall(r'<span class="d">([^<]+)<span class="t">（德）</span></span>', html)
    cc = collections.Counter(remaining)
    print(f'\n   剩餘未翻譯詞 (前40)：')
    for w, cnt in cc.most_common(40):
        print(f'     {cnt:3d}  {w}')
