# -*- coding: utf-8 -*-
import re, collections

M = {
    'jemanden':'某人', 'gehalten':'保持', 'zehn':'十',
    'lasst':'讓', 'akademischen':'學術的', 'brauchte':'需要',
    'verehren':'崇拜', 'Geleiten':'護送', 'Königs':'國王的',
    'Raphael':'拉斐爾', 'verbündet':'結盟', 'Auslandsstudium':'留學',
    'beschlossene':'已決定的', 'aufsteigen':'晉升', 'enthalten':'包含',
    'Begegnung':'相遇', 'unerlaubten':'未經許可的', 'Betretens':'進入',
    'Mädchenwohnheims':'女生宿舍的', 'triftigen':'正當的',
    'verweigern':'拒絕', 'nachdenkt':'想想', 'Schwächlings':'弱者的',
    'spielen':'比賽', 'verliert':'輸了', 'Klischeehaft':'老套地',
    'klischeehaft':'老套地', 'rauszumogeln':'矇混過關',
    'Nebencharakter-Kampf':'配角之戰', 'hinzulegen':'表現',
    'Inmitten':'在其中', 'Menschenmenge':'人群',
    'honigfarbenes':'蜂蜜色的', 'honigfarbene':'蜂蜜色的',
    'frisiert':'打理的', 'gelockt':'捲曲的', 'modische':'時尚的',
    'erstklassig':'一流的', 'Austauschstudentin':'交換生',
    'Präsidentin':'會長', 'Schülerrats':'學生會的',
    'talentiert':'有才華的', 'spendete':'給予了',
    'tosenden':'雷鳴般的', 'Beifall':'掌聲',
    'schrie':'喊道', 'Kämpfer':'鬥士',
    'seines':'他的', 'anfeuern':'加油',
    'Bühne':'舞台', 'hörbar':'可聽見地',
    'Staubkorn':'塵埃', 'Erdboden':'地面',
    'gleichzumachen':'夷為平地', 'klischeehafteste':'最老套的',
    'Niederlage':'失敗', 'hinlegen':'表演',
    'Reich':'帝國', 'Philosophie':'哲學',
    'betreten':'踏入', 'entwickelte':'展開了',
    'kündigte':'宣布了', 'Ansager':'主持人',
    'Sekunde':'秒', 'Nebencharakter-':'配角',
    'Aufregung':'興奮', 'Kannst':'你能',
    'mithalten':'跟上', 'äußersten':'極限的',
    'Nebencharakter-Kampfes':'配角之戰的',
    'beginnen':'開始', 'tanzte':'跳舞般地',
    'zielsichere':'精準的', 'Flugbahn':'軌跡',
    'einfacher':'更簡單', 'Millimeter':'毫米',
    'Klingen':'刀刃', 'kassieren':'挨打',
    'wehtun':'痛', 'stach':'刺了',
    'Augenblick':'瞬間', 'mitbekam':'察覺到了',
    'sprang':'跳了', 'Zehen':'腳尖',
    'benutzte':'利用了', 'Schwung':'衝力',
    'Angriffs':'攻擊的', 'Drehmoment':'旋轉力',
    'erzeugen':'產生', 'versteckten':'隱藏的',
    'Ärmeltasche':'袖口口袋', 'Beutel':'袋子',
    'Vortag':'前一天', 'vorbereitet':'準備好的',
    'geschleudert':'甩出了', 'Kreis':'圓圈',
    'Hiyaaaaaaaahhhhhhh':'嗨呀啊啊啊',
    'Spirale':'螺旋', 'Blutspritzern':'血花',
    'Nebencharakter-Geheimtechnik':'配角秘技',
    'Drehender':'旋轉', 'Sturz':'墜落',
    'Blutiger':'血染', 'Tornado':'龍捲風',
    'krachte':'撞上了', 'prallte':'彈了',
    'Lauter':'更大聲', 'donnerte':'怒吼道',
    'Ggh':'嗚', 'Gah':'嘎',
    'Blutbeutel':'血袋', 'spucken':'吐',
    'Perfekt':'完美', 'filmreifen':'電影般的',
    'Performance':'表演', 'grinsen':'笑',
    'Ughhhhhh':'嗚嗚嗚', 'verhielt':'表現得',
    'Sekunden':'秒', 'siebenundvierzig':'四十七',
    'Nebencharakter-Geheimtechniken':'配角秘技',
    'schauderte':'顫慄了', 'erhob':'站起了',
    'niederschlug':'打倒了', 'Chance':'機會',
    'aufgegeben':'放棄了', 'Wunder':'奇蹟',
    'mächtig':'強大的', 'kampfunfähig':'喪失戰鬥力',
    'Bloß':'只是', 'ein-':'一',
    'zweimal':'兩次', 'zehnmal':'十次',
    'erwischt':'擊中了', 'unbeugsamem':'不屈的',
    'jedes':'每一', 'gelang':'成功了',
    'Körperlich':'身體上', 'Kräfte':'力量',
    'Geist':'精神', 'mächtiger':'更強大',
    'physischen':'身體的', 'überschritten':'超越了',
    'Beinen':'腿', 'verblüffte':'震驚了',
    'aller':'所有人的', 'Fall':'不管怎樣',
    'Hauch':'一絲', 'Dies':'這',
    'Mut':'勇氣', 'körperlichen':'肉體的',
    'überwinden':'超越', 'herauszufordern':'挑戰',
    'rührte':'感動了', 'empfand':'感到了',
    'Respekt':'敬意', 'Verlangen':'渴望',
    'entschuldigen':'道歉', 'schwachen':'弱小的',
    'eingeschätzt':'看低了', 'unterlegen':'處於下風',
    'Herzen':'心底', 'beende':'結束',
    'weiterginge':'繼續', 'stürzen':'衝向',
    'strahlende':'燦爛的', 'Laufe':'過程中',
    'Kampfes':'戰鬥的', 'verstummte':'安靜了',
    'Beim':'在', 'verstört':'驚慌失措',
    'sprachlos':'說不出話', 'füllte':'充滿了',
    'magischen':'魔法的', 'eingesetzt':'使用了',
    'bebte':'震動了', 'geriet':'陷入了',
    'Aufruhr':'騷動', 'gibst':'你給',
    'brannten':'燃燒著', 'leidenschaftlicher':'更熱情',
    'Schlags':'一擊的', 'Fünkchen':'一點點',
    'erblicken':'看到', 'grenzenloser':'無盡的',
    'begegnete':'遇到了', 'summen':'嗡嗡聲',
    'Stopp':'停', 'Aufhören':'住手',
    'Schiedsrichter':'裁判', 'beendete':'結束了',
    'weiterzumachen':'繼續', 'weiterzukämpfen':'繼續戰鬥',
    'Unser':'我們的', 'Sieger':'勝者',
    'Ohrenbetäubender':'震耳欲聾的', 'gratulierte':'祝賀了',
    'Sieg':'勝利', 'übrigen':'其他的',
    'Geheimtechniken':'秘技', 'nächstes':'下一個',
    'aufheben':'保留', 'Gelegenheiten':'機會',
    'H-Hallo':'你、你好', 'unbekannten':'不認識的',
    'angesprochen':'搭話', 'drücken':'握',
    'zugesehen':'觀看了', 'A-Aha':'啊、原來',
    'Handbewegung':'手勢', 'gebracht':'帶來了',
    'unversehrten':'完好的', 'schlimm':'嚴重',
    'verstümmeln':'弄殘', 'Eingänge':'入口',
    'Zuschauer':'觀眾', 'aufhielten':'逗留',
    'gucke':'看看', 'aufgestanden':'站起來了',
    'Zuschauern':'觀眾們', 'Sorte':'類型的',
    'kleines':'小小的', 'Päckchen':'小包',
    'gebacken':'烤的', 'Gegenleistung':'回報',
    'Dankeschön':'謝禮', 'spannenden':'精彩的',
    'fröhlich':'開心地', 'W-Wenn':'如、如果',
    'ausmacht':'介意', 'Ausnahme':'例外',
    'Entschluss':'決心', 'Verlegenheit':'害羞',
    'Super':'太好了', 'älteren':'年長的',
    'grauem':'灰色的', 'gekämmtem':'梳理好的',
    'zukam':'走過來', 'dünnen':'細框的',
    'berühmter':'著名的', 'nannte':'稱為',
    'Recherchen':'調查', 'Potenzial':'潛力',
    'Hauptcharakter':'主角', 'Hauptcharakteren':'主角們',
    'Ratschlägen':'建議', 'lüften':'揭開',
    'Erfindungen':'發明', 'Bosse':'老大們',
    'ausging':'以為', 'Gleichfalls':'彼此彼此',
    'zurückgehalten':'隱瞞了', 'nachdenklich':'沉思地',
    'Kinn':'下巴', 'Vermutlich':'大概',
    'verletzen':'傷害', 'aufsuchen':'去找',
    'Meine':'我的', 'forscht':'在研究',
    'Lachend':'笑著', 'fuhr':'繼續說',
    'durchmachen':'經歷', 'hoffe':'希望',
    'Sieh':'你看', 'Vaters':'父親的',
    'schaute':'看著', 'peinlich':'尷尬的',
    'Nebencharakteren':'配角們', 'befreundet':'交朋友',
    'klopfte':'敲了', 'kennenzulernen':'認識',
    'besorgten':'擔心的', 'Versprochen':'保證',
    'trinken':'喝', 'blendend':'很好',
    'tranken':'喝著', 'aßen':'吃著',
    'verabschiedeten':'告別了', 'voneinander':'彼此',
    'Unterhaltung':'聊天', 'Eindruck':'印象',
    'normales':'普通的', 'beauftragt':'委託了',
    'wichtiges':'重要的', 'Ziemlich':'相當',
    'beeindruckend':'令人印象深刻', 'total':'完全',
    'allem':'一切', 'entfernt':'遠',
    'passende':'合適的', 'Freundin':'女朋友',
    'kaum':'幾乎不', 'fünf':'五',
    'krankschreiben':'請病假', 'Verdacht':'嫌疑',
    'erregen':'引起', 'zurückkehrte':'回來了',
    'netter':'善良的', 'flauschig':'毛茸茸的',
    'Gerade':'剛好', 'krankgeschrieben':'請了病假',
    'erholen':'休息', 'gehe':'去',
    'getrunken':'喝了', 'verausgabt':'累壞了',
    'sorgte':'讓', 'besuchen':'去看',
    'aufdringlich':'打擾', 'solche':'這種',
    'Vorerst':'暫時', 'irgendwann':'總有一天',
    'einschlief':'睡著了', 'Schreibtischschublade':'書桌抽屜',
    'verzierte':'裝飾的', 'duftete':'飄著香氣',
    'herrlich':'美妙地', 'Angeblich':'據說',
    'ineinander':'互相', 'verliebt':'相愛了',
    'Gerüchten':'傳聞', 'vorgedrungen':'傳開了',
    'verlieh':'賦予了', 'Glaubwürdigkeit':'可信度',
    'Vorhänge':'窗簾', 'flatterten':'飄動著',
    'nachdenken':'思考', 'voranbringen':'推進',
    'nachzufragen':'詢問', 'Lust':'想',
    'arbeiten':'工作', 'Flauschige':'毛茸茸的',
    'schweben':'飄浮', 'Nachmittagssonne':'午後陽光',
    'Egal':'無所謂', 'Teetrinken':'喝茶',
    'pochte':'敲著', 'Zimmers':'房間的',
    'Mädchenwohnheim':'女生宿舍', 'zurzeit':'目前',
    'Hausarrest':'禁足', 'entschuldige':'抱歉',
    'aufschlage':'翻開', 'eintreten':'進來',
    'geräumig':'寬敞的', 'durchschnittlichen':'普通的',
    'Schülers':'學生的', 'n-nicht':'不、不是',
    'D-Dann':'那、那就', 'nehme':'拿',
    'Kommt':'過來', 'nervöser':'更緊張',
    'brühte':'泡了', 'gebe':'給',
    'königlichen':'王室的', 'Ließ':'讓',
    'kochen':'煮', 'zusammenreißen':'振作',
    'hergekommen':'來的', 'zuckte':'縮了一下',
    'verschreckt':'嚇到了', 'Kalteetassen':'冷茶杯',
    'klirrten':'叮噹響', 'beklemmenden':'壓抑的',
    'Tisch':'桌子', 'V-Vielen':'非、非常',
    'gegenüber':'對面的', 'bitter':'苦的',
    'geflüstert':'低聲說了', 'schüttete':'倒了',
    'reichlich':'大量的', 'trank':'喝了',
    'Fr-Freut':'很、很高興', 'Mitsugoshi-Kaufhauses':'三越百貨的',
    'Freut':'高興', 'Schokoladengeschäft':'巧克力店',
    'Deren':'那個', 'cremig':'醇厚的',
    'Geschmack':'味道', 'beschrieb':'描述著',
    'unbeholfen':'笨拙地', 'Seid':'你們是',
    'beobachtete':'觀察著', 'wahren':'真正的',
    'Absichten':'意圖', 'abzulesen':'看出',
    'wanderte':'游移著', 'hektisch':'慌張地',
    'Schultern':'肩膀', 'angespannt':'緊繃的',
    'Natur':'天性', 'Umgang':'相處',
    'bezweckte':'目的是', 'Bestes':'最好的',
    'klang':'聽起來', 'wart':'你們在',
    'Abwechslung':'換換口味', 'verschiedenen':'各種的',
    'Gründen':'原因', 'kicherte':'偷笑了',
    'H-Hast':'你、你有', 'neugierig':'好奇地',
    'Ähm':'呃', 'wolltest':'你想要',
    'leer':'空了', 'danke':'謝謝',
    'Gegensatz':'相反', 'Ankunft':'到來',
    'strahlenden':'燦爛的', 'erklang':'響起了',
    'Klirren':'叮噹聲', 'zerbrochen':'碎了',
    'glückliche':'幸福的',
}

with open('page6.html', 'r', encoding='utf-8') as f:
    html = f.read()

def replace_unknown(m):
    word = m.group(1)
    if word in M:
        zh = M[word]
        return f'<span class="d">{word}<span class="t">{zh}</span></span>'
    return m.group(0)

html = re.sub(
    r'<span class="d">([^<]+)<span class="t">（德）</span></span>',
    replace_unknown,
    html
)

d_count = len(re.findall(r'<span class="d">', html))
c_count = len(re.findall(r'<span class="c">', html))
unknown = len(re.findall(r'（德）', html))

with open('page6.html', 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✅ 完成')
print(f'   德文詞 (.d): {d_count}')
print(f'   中文互動詞 (.c): {c_count}')
if d_count + c_count > 0:
    print(f'   德文佔比: {d_count/(d_count+c_count)*100:.1f}%')
print(f'   未翻譯: {unknown}')
