# -*- coding: utf-8 -*-
import re, collections

M = {
    'Aula':'禮堂', 'Habgier':'貪婪', 'dafür':'為此',
    "Rex'":'雷克斯的', 'Marco':'馬可', 'Keller':'地下室',
    'Klassenzimmers':'教室的', 'Blockade':'封鎖', 'retten':'拯救',
    'setzen':'坐下', 'Fenster':'窗戶', "geht's":'走吧',
    'warf':'扔了', 'pfeifendes':'呼嘯的',
    'Schrei':'尖叫', 'einzigen':'唯一的', 'Umgebung':'周圍',
    'abgerissen':'被扯掉了', 'endete':'結束了', 'Rede':'講話',
    'ungefähr':'大約', 'blockiert':'被封鎖了',
    'Terroristen':'恐怖分子', 'Männern':'男人們',
    'abzuwehren':'抵擋', 'auszuweichen':'閃避',
    'miteinander':'互相', 'Schülern':'學生們',
    'vergewisserte':'確認了', 'diesmal':'這次',
    'überprüfte':'檢查了', 'richtete':'對準了',
    'entschlüsselt':'解讀了', 'Löwenmähne':'獅子鬃毛',
    'Probleme':'問題', 'Sinn':'意義',
    'Kugel':'球', 'Schleimkugel':'史萊姆球',
    'wuselte':'跑來跑去', 'Schreibtisch':'書桌',
    'absorbiert':'吸收', 'speichern':'儲存',
    'Zeitraum':'時間', 'Steuergerät':'控制器',
    'Regal':'書架', 'Adoptivvater':'養父',
    'Stock':'層樓', 'Mageren':'瘦子', 'Magere':'瘦子',
    'Handflächenschlag':'掌擊', 'schützte':'保護了',
    'modifizieren':'改造', 'Lampe':'燈',
    'Schülerrat':'學生會', 'Oberstufler':'高年級生',
    'raus':'出去', 'feine':'細微的',
    'gestürmt':'衝進了', 'Bleibt':'留在',
    'Streich':'惡作劇', 'meinten':'是說',
    'wovon':'關於什麼', 'Kindheit':'童年',
    'hindurch':'穿過', 'übernommen':'接管了',
    'Verdammt':'該死', 'verdammt':'該死的',
    'Oberkörper':'上半身', 'Bewegung':'動作',
    'fühlen':'感覺', 'gestanden':'站著',
    'hallte':'迴盪著', 'hinterlassen':'留下了',
    'hustete':'咳嗽了', 'atmen':'呼吸',
    'erreicht':'到達了', 'unzählige':'無數',
    'Seinen':'他的', 'Technik':'技術',
    'Nähe':'附近', 'wirken':'起作用',
    'einsetzte':'使用了', 'Herzstillstand':'心臟停止',
    'längeren':'較長的', 'überleben':'存活',
    'Risiko':'風險', 'manchmal':'有時候',
    'Aua':'好痛', 'frische':'新鮮的',
    'tanzten':'跳動著', 'Stühle':'椅子',
    'Zeichen':'符號', 'Artefakts':'文物的',
    'beschäftigt':'忙碌的', 'Labors':'研究室的',
    'Feder':'羽毛筆', 'Papier':'紙',
    'konzentrierte':'專注著', 'kratzte':'沙沙地寫著',
    'praktisch':'實際上', 'versteckte':'隱藏的',
    'ausgemergelten':'骨瘦如柴的', 'Streuners':'流浪者的',
    'Verarsch':'開什麼玩笑', 'erbebte':'顫動了',
    "sich's":'自己', 'versah':'察覺',
    'Gar':'根本', 'Kräfteunterschied':'實力差距',
    'Schließlich':'畢竟', 'normalerweise':'通常',
    'hielten':'守著', 'Außerhalb':'在外面',
    'mitbekommen':'察覺到', 'kichern':'偷笑',
    'vertreiben':'消磨', 'Mänteln':'斗篷',
    'auftauchen':'出現', 'Outfits':'裝扮',
    'durchschlug':'擊穿了', 'durchbohrt':'貫穿了',
    'erwischen':'抓住', 'suche':'找',
    'gegenüberliegenden':'對面的', 'hinunter':'向下',
    'weiterer':'又一個', 'bewegt':'移動了',
    'entdeckte':'發現了', 'Deckung':'掩護',
    'Puh':'呼', 'rappelte':'爬起來了',
    'guckte':'看了看', 'watschelte':'搖搖晃晃走著',
    'Diesmal':'這次', 'durchs':'穿過',
    'lauten':'巨大的', 'Endlich':'終於',
    'solchen':'這種', 'Situationen':'情況',
    'drauf':'等的就是', 'stapelten':'堆滿了',
    'herein':'進來', 'durchwühlen':'翻找',
    'Ursache':'原因', 'Magieblockade':'魔力封鎖',
    'freisetzen':'釋放', 'Gefecht':'戰鬥',
    'befreien':'解放', 'unterstützt':'支援了',
    'mehrere':'數個', 'Ritters':'騎士的',
    "hab's":'我搞定了', 'Dritte':'第三',
    'vitalen':'要害的', 'Typ':'傢伙',
    'früheres':'之前的', 'Untergebener':'部下',
    'blutigen':'血腥的', 'bewusstlos':'昏迷的',
    'angegriffen':'攻擊了', 'allesamt':'全部',
    'linker':'左邊的', 'Intuition':'直覺',
    'Schnelligkeit':'速度', 'menschlichen':'人類的',
    'Limit':'極限', 'letztes':'最後的',
    'Nus':'努的', 'Ritterkommandant':'騎士團長',
    'Verlobter':'未婚夫', 'vorbestimmter':'命定的',
    'umzingelt':'被包圍了', 'Magiestein':'魔力石',
    'Artefakten':'文物', 'Hals':'脖子',
    'Buch':'書', 'allmählich':'漸漸地',
    'gegangen':'走了', 'Labyrinth':'迷宮',
    'Gänge':'通道', 'Karte':'地圖',
    'Lüftungsschacht':'通風管道',
    'Rückkehr':'回來', 'morgendliche':'早上的',
    'bleibt':'留下', 'Kandidatin':'候選人',
    'begleitet':'陪伴', 'kurze':'短暫的',
    'Lus':'魯的', 'sinnlose':'無意義的',
    'gähnte':'打了個哈欠', 'Woche':'週',
    'Ausflug':'遠足', 'weiterreden':'繼續說',
    'Schülerinnen':'女學生們', 'traten':'走進了',
    'bekanntes':'熟悉的', 'stylish':'時髦的',
    'gewohnt':'習慣的', 'Ging':'怎麼了',
    'Gefasel':'廢話', 'gelangweilt':'無聊地',
    'gähnten':'打著哈欠', 'Notizen':'筆記',
    'irgendeinen':'某個', 'besiegt':'打敗了',
    'guckt':'看著', 'zupfte':'拽了拽',
    'zurecht':'整理', 'dabeihaben':'帶著',
    'hör':'聽我說', 'redeten':'聊著',
    'komisches':'奇怪的', 'Irgendetwas':'有什麼東西',
    'reflexartig':'反射性地', 'angewöhnt':'養成了',
    'konstant':'持續地', 'manipulieren':'操控',
    'spüren':'感知', 'Fluss':'流動',
    'blockieren':'封鎖', 'entweder':'要嘛',
    'Gewalt':'暴力', 'durchbrechen':'突破',
    'umgehen':'繞過', 'feiner':'更細緻的',
    'kommt':'來了', 'gewaltige':'巨大的',
    'Explosion':'爆炸', 'aufgesprengt':'炸開了',
    'Panik':'恐慌', 'gezogenen':'拔出的',
    'schrien':'尖叫著', 'blockierten':'封鎖了',
    'Ausgang':'出口', 'panischen':'恐慌的',
    'übertönt':'蓋過了', 'Meinten':'他們說的是',
    'begriffen':'明白了', 'verstand':'理解了',
    'todernst':'非常嚴肅', 'Gleiche':'一樣的',
    'Klassen':'班級', 'bewundern':'崇拜',
    'träumten':'夢想著', 'wünschten':'渴望著',
    'griffen':'拿起了', 'gerührt':'感動',
    'fantasiert':'幻想過', 'Hunderte':'數百',
    'Tausende':'數千', 'Milliarden':'數十億',
    'Male':'次', 'geträumt':'夢到過',
    'nehmt':'拿走', 'schüchterten':'威嚇著',
    'bewusst':'清楚地', 'Terrorist':'恐怖分子',
    'Rollen':'角色', 'leichtere':'較輕的',
    'Unendliche':'無限地', 'versteht':'理解',
    'würdevolle':'有尊嚴的', 'angreifen':'攻擊',
    'hochnehmen':'逮住', 'Göre':'小丫頭',
    'dünnes':'纖細的', 'Exempel':'殺雞儆猴',
    'statuieren':'以儆效尤', 'bemerkt':'注意到了',
    'begriff':'意識到了', 'weitergeht':'繼續',
    'schwarzes':'黑色的', 'unmöglich':'不可能的',
    'Ablauf':'過程', 'falsch':'錯誤的',
    'Hirn':'腦子', 'beschleunigte':'加速了',
    'langsamer':'更慢', 'endlose':'無盡的',
    'Frustration':'挫敗感', 'nähernde':'逼近的',
    'aufblitzen':'閃過', 'Verletzung':'傷害',
    'flach':'平躺', 'wegzudrehen':'轉開',
    'frustrierte':'受挫的', 'akzeptieren':'接受',
    'unmittelbar':'就在', 'weggestoßen':'推開了',
    'seitlich':'從側面', 'zugeflogen':'飛來的',
    'Aahh':'啊', 'Reflexartig':'反射性地',
    'töteten':'殺了', 'unverzeihlich':'不可原諒的',
    'AAAAAAAAHHHHHH':'啊啊啊啊啊啊',
    'Hört':'停', 'auuuuuuuuuuuuuuuuuuuuf':'下來',
    'schockierenden':'令人震驚的', 'Szene':'場景',
    'Blutlache':'血泊', 'reglos':'一動不動地',
    'tödlich':'致命的', 'Arme':'手臂',
    'bleibenden':'永久的', 'beschützt':'保護了',
    'riskieren':'冒險', 'blasser':'更蒼白的',
    'landeten':'落下了', 'Blutspritzer':'血跡',
    'blutverschmiertem':'沾滿血的', 'zufriedenen':'滿意的',
    'gesetzt':'放好了', 'erwidern':'回應',
    'schwor':'發誓了', 'Opfer':'犧牲',
    'wunderbar':'很好', 'biss':'咬著',
    'Unterlippe':'下唇', 'gehorchen':'聽從',
    'hängen':'掛著', 'geschworen':'發過誓',
    'rächen':'報仇', 'Zeitpunkt':'時機',
    'floss':'流淌著', 'umarmte':'擁抱了',
    'leblosen':'毫無生氣的', 'Schluchzen':'嗚咽',
    'beeindruckenden':'令人印象深刻的', 'angesehen':'看著',
    'dumm':'笨', 'Stellung':'姿態',
    'setzten':'擺出了', 'befahlen':'命令',
    'hinzustellen':'擺出', 'fesselten':'綁住了',
    'nacheinander':'一個接一個', 'niemanden':'任何人',
    'widersetzte':'反抗了', 'verharrten':'靜止不動',
    'leblose':'毫無生氣的', 'trieb':'驅使著',
    'verhallte':'消散了', 'Faust':'拳頭',
    'Beweg':'動', 'schooooooon':'啊啊啊啊',
    'angehalten':'停下', 'Zehn-Minuten-':'十分鐘',
    'Herzensbrecher':'萬人迷', 'winzige':'微小的',
    'aufschlitzen':'劃開', 'tödliche':'致命的',
    'vermeiden':'避免', 'überzeugend':'逼真地',
    'mithilfe':'借助', 'verarzten':'治療',
    'möglichst':'盡量', 'fein':'精細地',
    'umging':'繞開了', 'Ansonsten':'否則',
    'überwältigenden':'壓倒性的', 'gewaltsam':'強行',
    'auffallen':'引起注意', 'Bewegungen':'動作',
    'behindern':'妨礙', 'überlebt':'活了下來',
    'Hirndurchblutung':'腦部供血', 'aufrechtzuerhalten':'維持',
    'längerfristige':'長期的', 'Folgen':'後遺症',
    'barg':'有著', 'tastete':'摸索著',
    'Weil':'因為', 'Körpers':'身體的',
    'zerzauste':'吹亂了', 'Nachmittagsbrise':'午後微風',
    'wehte':'吹著', 'weißen':'白色的',
    'flattern':'飄動', 'Umgeworfene':'翻倒的',
    'zerstörte':'被破壞的', 'Türen':'門',
    'Blutfleck':'血跡', 'gestörten':'被打破的',
    'Normalität':'日常', 'leeren':'空蕩蕩的',
    'stillen':'安靜的', 'Entschlüsselung':'解讀',
    'Tumult':'騷動', 'außerhalb':'在外面',
    'schmal':'窄小的', 'Weder':'既不',
    'Explosionen':'爆炸', 'Irgendjemand':'有人',
    'greift':'在攻擊', 'entging':'逃過了',
    'vertieft':'專注著', 'neigte':'傾向',
    'Ausmaß':'規模', 'Bedeutendes':'重大的事',
    'raubte':'搶走了', 'Glasscherbe':'玻璃碎片',
    'verschmierte':'抹了', 'Guardian':'守護者',
    'dürft':'你們可以', 'geehrt':'榮幸',
    'nervt':'煩死了', 'Draufgängertyp':'衝動的人',
    'matten':'疲憊的', 'erschrak':'嚇了一跳',
    'vorhabt':'打算', 'denkt':'以為',
    'ungeschoren':'安然無恙地', 'davonkommt':'逃脫',
    'angreift':'攻擊', 'übrigens':'順帶一提',
    'irres':'瘋狂的', 'Tu':'做',
    'scheißegal':'管他的', 'holen':'去拿',
    'aussieht':'看起來', 'Wisst':'你們知道',
    'sprichst':'你說的', 'Angesichts':'面對',
    'Mienen':'表情', 'breit':'寬寬地',
    'erschütterte':'震動了', 'löste':'引發了',
    'Druckwelle':'衝擊波', 'schreien':'尖叫',
    'Fast':'幾乎', 'wem':'誰',
    'halb':'半', 'verhungertes':'飢餓的',
    'Raubtier':'野獸', "wär's":'怎麼樣',
    'Mädel':'小妞', 'Lebewohl':'永別',
    'Hieb':'一砍', 'Ängstlich':'害怕地',
    'gezogenem':'拔出的', 'unserem':'我們的',
    'Vizekommandant':'副團長', 'Dich':'你',
    'Lauf':'快跑', 'Ohren':'耳朵',
    'Todesschreie':'慘叫聲', 'Überblick':'全局',
    'verschaffen':'取得', 'zusammenkamen':'聚集',
    'fanden':'發現了', 'Einführungsveranstaltungen':'開幕活動',
    'berühmte':'著名的', 'Vorträge':'演講',
    'Theaterstücke':'戲劇', 'aufgeführt':'上演',
    'Schülerschaft':'學生們', 'versammeln':'聚集',
    'scharten':'聚攏了', 'Grenze':'邊界',
    'blockierte':'封鎖了', 'verbliebenen':'剩餘的',
    'Ausschau':'搜尋', 'herabsah':'俯視著',
    'mysteriöse':'神秘的', 'Terrororganisation':'恐怖組織',
    'Geiseln':'人質', 'Liste':'清單',
    'streichen':'劃掉', 'Geschehen':'事件',
    'betrachten':'觀看', 'Erledigt':'搞定了',
    'Ästhetik':'美學', 'grelle':'刺眼的',
    'Mittagssonne':'正午的太陽', 'blauer':'蔚藍的',
    'Brise':'微風', 'Voll':'完全',
    'widerlich':'噁心', 'entscheidenden':'關鍵的',
    'begangen':'犯下了', 'Anlass':'場合',
    'abgestimmt':'搭配的', 'kleiden':'穿著',
    'koordiniert':'協調的', 'geschmacklos':'沒品味',
    'Lange':'長長的', 'Mäntel':'斗篷',
    'getragen':'穿過', 'vorgehabt':'打算過',
    'angehen':'面對', 'Spaß':'樂趣',
    'schade':'可惜', 'totschlagen':'打發',
    'grübelnd':'沉思地', 'hinunterblickte':'往下看著',
    'entlanggehen':'沿著走', 'lächerlich':'可笑的',
    'helllichten':'光天化日的',
}

TARGET = 'page8.html'

with open(TARGET, 'r', encoding='utf-8') as f:
    html = f.read()

def repl(m):
    w = m.group(1)
    if w in M:
        return f'<span class="d">{w}<span class="t">{M[w]}</span></span>'
    return m.group(0)

html = re.sub(r'<span class="d">([^<]+)<span class="t">（德）</span></span>', repl, html)

import re
d = len(re.findall(r'<span class="d">', html))
c = len(re.findall(r'<span class="c">', html))
u = len(re.findall(r'（德）', html))

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✅ page8.html 翻譯完成')
print(f'   d={d} c={c} 佔比={d/(d+c)*100:.1f}% 未翻譯={u}')

if u > 0:
    remaining = re.findall(r'<span class="d">([^<]+)<span class="t">（德）</span></span>', html)
    cc = collections.Counter(remaining)
    print(f'   剩餘 (前20):')
    for w,cnt in cc.most_common(20):
        print(f'     {cnt:3d}  {w}')
