# -*- coding: utf-8 -*-
import re, collections

M = {
    'spiel':'演', 'Scharfschütze':'狙擊手', 'daumengroßes':'拇指大的',
    'Schleim':'史萊姆', 'Bodysuit':'緊身衣', 'stehst':'站在',
    'Schusslinie':'射線上', 'Schnipsen':'彈指', 'pfeifenden':'呼嘯的',
    'wahrlich':'真是', 'schießen':'射擊', 'Zielfernrohr':'瞄準鏡',
    'Akademiegebäude':'學院建築', 'Idiotin':'笨蛋', 'ziellos':'漫無目的地',
    'rennen':'跑', 'erfasst':'捕捉到了', 'dauernd':'一直',
    'entdeckt':'發現了', 'Anstalten':'打算',
    'zielte':'瞄準了', 'platzte':'衝了進來',
    'Mission':'任務', 'accomplished':'完成',
    'Blickfeld':'視野', 'heckt':'在搞什麼',
    'Nebencharakter-Intuition':'配角直覺',
    'Hauptszenario':'主線劇情', 'voranschritt':'推進著',
    'Höhepunkt':'高潮', 'Hauptszenarios':'主線劇情的',
    'leitete':'引導著', 'Akademiegebäudes':'學院建築的',
    'schnappte':'搶到了', 'Fensterrahmen':'窗框',
    'verdächtig':'可疑的', 'fällst':'你會掉進',
    'schlich':'潛行著', 'ran':'靠近',
    'erwischte':'抓到了', 'irgendein':'某個',
    'leerer':'空蕩蕩的', 'eingebildet':'自以為',
    'ahnte':'預感到', 'unternehmen':'採取行動',
    'bog':'轉了彎', 'betete':'祈禱著',
    'lugte':'偷看著', 'linste':'窺探著',
    'Wieder':'又', 'ängstlich':'害怕地',
    'Ecken':'角落', 'Korridore':'走廊',
    'Gebäude':'建築', 'unvorsichtiger':'更不小心',
    'stolperte':'絆到了', 'fliegende':'飛來的',
    'Aaahhh':'啊啊啊', 'kennengelernt':'認識了',
    'davongekommen':'脫身了', 'müde':'厭倦了',
    'genervt':'煩躁的', 'wirkenden':'看起來的',
    'Tipps':'建議', 'Hör':'聽我說',
    'lauf':'快跑', 'pass':'小心',
    'gefälligst':'給我', 'hintrittst':'踩到',
    'Schuhen':'鞋子', 'rausbekommen':'弄到',
    'Büro':'辦公室', 'Vize-Schulleiters':'副校長的',
    'Stocks':'樓的', 'massive':'巨大的',
    'Mitte':'中間', 'Möbel':'家具',
    'Wänden':'牆壁上', 'reihten':'排列著',
    'Nebenfigur':'配角', 'Szenario':'劇情',
    'ausgearbeitet':'制定了', 'reiflicher':'深思熟慮',
    'Überlegung':'考慮', 'Position':'位置',
    'hilfreichen':'有幫助的', 'einzunehmen':'佔據',
    'dürfte':'應該', 'Niemals':'絕不',
    'Dokument':'文件', 'hervor':'出來',
    'Buchstaben':'字母', 'Zahlen':'數字',
    'mathematische':'數學的', 'Formeln':'公式',
    'Bücherregale':'書架', 'Unterlagen':'資料',
    'Norden':'北方', 'Fiel':'掉了',
    'stylishe':'時髦的', 'Erwachsenen':'大人',
    'Schreibtischschubladen':'書桌抽屜',
    'Versuch':'嘗試', 'Lärm':'噪音',
    'Schopf':'頭髮', 'zweifellos':'毫無疑問',
    'Allein':'光是', 'Schwerpunktszenario':'重點劇情',
    'schaurig':'可怕的', 'Zeichnung':'設計圖',
    'Tischtennisball':'乒乓球', 'akkumuliert':'累積',
    'Aktiviert':'啟動後', 'Radius':'半徑',
    'Wellenlängen':'波長', 'Voraus':'提前',
    'ausgeschlossene':'被排除的', 'wahnsinnig':'瘋狂的',
    'starke':'強大的', 'fähig':'有能力的',
    'gefährlichen':'危險的', 'akkumulierte':'累積的',
    'ursprünglicher':'原本的', 'längere':'較長的',
    'Zeiträume':'時段', 'defekt':'故障的',
    'klassifiziert':'歸類為', 'proppenvoll':'擠滿了',
    'Magierittern':'魔法騎士們', 'gesammelte':'收集的',
    'dreckig':'骯髒的', 'Kombination':'組合',
    'defektes':'故障的', 'kombinierter':'結合的',
    'Form':'形式', 'kurzzeitig':'短暫地',
    'jagen':'追趕', 'entpuppt':'原來是',
    'Forschungsergebnisse':'研究成果',
    'veröffentlicht':'發表了', 'Aufbewahrung':'保管',
    'passieren':'發生', 'Ding':'東西',
    'gestohlen':'偷走了', 'Möglichkeit':'可能性',
    'aufzuhalten':'阻止', 'aktivieren':'啟動',
    'Auges':'眼睛的', 'oberen':'上面的',
    'Stockwerken':'樓層', 'patrouilliert':'巡邏著',
    'nähern':'靠近', 'Bücher':'書',
    'frei':'空的', 'Geheimgänge':'密道',
    'gefallen':'掉下去', 'Überall':'到處',
    'Fluchtwege':'逃生路線', 'traurig':'遺憾地',
    'staubig':'佈滿灰塵', 'Fußabdrücke':'腳印',
    'gehofft':'期望', 'Geheimgang':'密道',
    'Ursprünglich':'原本', 'starb':'去世了',
    'aufgezogen':'養大了', 'eigene':'自己的',
    'bereitete':'準備了', 'Fantastischer':'太棒了',
    'Juhu':'耶', 'Entschlüsseln':'解讀',
    'tut':'會', 'weh':'痛',
    'Zum':'到', 'bräuchte':'需要',
    'Unterstützung':'支援', 'Pass':'小心',
    'schaffst':'你做得到', 'befasste':'投入了',
    'tollen':'很棒的', 'Typen':'人',
    'geholfen':'幫了', 'rauskommst':'出來',
    'werfe':'扔', 'aktivierte':'啟動了',
    'kaputt':'壞掉了', 'kaputtgeht':'壞掉',
    'schwammig':'模糊的', 'regeln':'處理',
    'danken':'感謝', 'tolle':'了不起的',
    'stolzierte':'昂首走著', 'gingen':'走了',
    'wagte':'敢', 'anzusehen':'看',
    'Gewölbe':'地下室', 'reichte':'夠了',
    'Ausgänge':'出口', 'bewacht':'被看守著',
    'ständiger':'持續的', 'Beobachtung':'監視',
    'schiefen':'歪斜的', 'Hinterzimmer':'密室',
    'sitzender':'坐著的', 'durchdringend':'銳利的',
    'verdeckt':'遮住', 'gekleidete':'穿著的',
    'äußerlich':'外表上', 'unterschied':'區分',
    'bleib':'保持', 'locker':'放鬆',
    'Magerer':'瘦子', 'lungern':'閒逛',
    'frage':'問', 'verbannte':'趕走了',
    'sauer':'生氣的', 'bekommen':'得到',
    'Unfug':'胡鬧', 'Pläne':'計劃',
    'gestört':'打擾了', 'Mist':'糟糕',
    'baust':'搞出', 'leg':'別',
    'streng':'嚴厲地', 'erhobenen':'舉起的',
    'fällt':'掉下來', 'Starkes':'強大的',
    'Reaktion':'反應', 'schweigend':'沉默地',
    'weiterzuerzählen':'告訴別人', 'zerquetscht':'壓碎了',
    'Löcher':'洞', 'zugefügt':'造成了',
    'redete':'說著', 'hungriger':'飢餓的',
    'Wolf':'狼', 'Solltest':'你應該',
    'lieber':'最好', 'Rundenmitglied':'巡邏成員',
    'bekommst':'你會得到', 'Bring':'帶來',
    'Eindringlings':'入侵者的', 'grässlich':'可怕的',
    'leuchtendes':'發光的', 'ominösen':'不祥的',
    'Glitzern':'閃光', 'zurückkehren':'回去',
    'unheimliches':'詭異的', 'entlanggingen':'走過',
    'Suche':'搜索', 'bizarren':'怪異的',
    'Phänomen':'現象', 'heimgesucht':'被侵襲了',
    'urplötzlich':'突如其來地', 'verstehen':'理解',
    'Ungewöhnliches':'異常的東西', 'abermals':'再次',
    'zweiter':'第二個', 'entdecken':'發現',
    'geschlagen':'打了', 'mitgenommen':'受傷的',
    'Sehkraft':'視力', 'Äußerste':'極限的',
    'verstärkte':'增強了', 'ausmachen':'辨認',
    'Aufgepasst':'小心', 'fassen':'抓住',
    'sollen':'應該', 'nirgends':'哪裡都',
    'Ehe':'在……之前', 'Leibeskräften':'全力',
    'schützen':'保護', 'Gugh':'嗚',
    'dumpfen':'沉悶的', 'Ton':'聲音',
    'ekelhaften':'噁心的', 'brechenden':'斷裂的',
    'V-Verdammt':'該、該死', 'verstärkter':'增強的',
    'Hätte':'要是', 'geschützt':'保護了',
    'Getrieben':'驅使著', 'pure':'純粹的',
    'Timing':'時機', 'verfehlte':'沒打中',
    'blitzschnell':'閃電般地', 'Dafür':'為此',
    'brachen':'斷了', 'Momentum':'氣勢',
    'nutzte':'利用了', 'verfolgen':'追擊',
    'Gegenangriff':'反擊', 'starten':'發動',
    'bisher':'至今', 'Einziger':'唯一的',
    'Objektiv':'客觀地', 'befunden':'處於',
    'starkes':'強大的', 'jenseits':'超越了',
    'Preis':'代價', 'Beweise':'證據',
    'erkannt':'識破了', 'gelöst':'解開了',
    'unvergleichliche':'無與倫比的', 'Geschwindigkeit':'速度',
    'Schaden':'傷害', 'Bald':'很快',
    'stoßen':'碰上', 'vollständig':'完全地',
    'entlarven':'揭穿', 'raten':'勸告',
    'gewonnenem':'贏得的', 'Dessen':'對此',
    'überstieg':'超過了', 'normalen':'正常的',
    'Nachteil':'劣勢', 'täuschen':'欺騙',
    'hältst':'你以為', 'Schwarze':'黑色的',
    'hämisch':'嘲諷地', 'Sicht':'角度',
    'leisten':'承受', 'unachtsam':'大意',
    'unsichtbaren':'看不見的', 'ausweichen':'閃避',
    'selbstbewusst':'自信地', 'hochgradige':'高度的',
    'psychologische':'心理', 'Kriegsführung':'戰術',
    'Angsthase':'膽小鬼', 'überließ':'交給了',
    'beugte':'彎下了', 'Handflächenschlags':'掌擊的',
    'Gaaaah':'嘎啊', 'schiere':'純粹的',
    'Willenskraft':'意志力', 'Somit':'因此',
    'KOMM':'來', 'SCHON':'啊',
    'Punkte':'要害', 'standhalten':'承受住',
    'empfing':'接下了', 'GAGH':'嘎',
    'AAAAAHHHH':'啊啊啊', 'davongeschleudert':'被彈飛了',
    'Tische':'桌子', 'inneren':'內部的',
    'Organe':'器官', 'lebte':'活著',
    'Bemühungen':'努力', 'verteidigen':'保護',
    'ausgezahlt':'有回報了', 'Hölle':'地獄',
    'Leichen':'屍體', 'wiesen':'顯示著',
    'äußere':'外部的', 'gänzlich':'完全',
    'Hatte':'難道', 'erklangen':'響起了',
    'verstummten':'安靜了', 'bemerkte':'注意到了',
    'schwitzte':'冒著汗', 'Türknauf':'門把',
    'Quietschen':'吱嘎聲', 'durchbrach':'打破了',
    'Ahhhh':'啊啊啊', 'Körperteil':'身體部位',
    'überwunden':'克服了', 'Hammer':'太厲害了',
    'Letzte':'最後的', 'dunkelbraune':'深棕色的',
    'unauffällig':'低調的', 'anzog':'穿上了',
    'Sexappeal':'性感魅力', 'verstecken':'隱藏',
    'zerstörten':'被破壞的', 'hinab':'向下',
    'berühmt':'有名的', 'beraubt':'被搶走了',
    'ausrichten':'對抗', 'gequältem':'痛苦的',
    'Leichnam':'遺體', 'Leere':'空虛',
    'Granger':'格蘭傑', 'angeschlossen':'加入了',
    'gepflegter':'整潔的', 'starker':'強烈的',
    'zufolge':'根據', 'künftige':'未來的',
    'Rückblickend':'回想起來', 'ausgeprägten':'強烈的',
    'Gerechtigkeit':'正義', 'tauschten':'交換了',
    'Briefe':'信件', 'zahlreichen':'眾多的',
    'Bällen':'舞會', 'Eltern':'父母',
    'ausgesucht':'挑選了', 'entwickeln':'發展',
    'liebte':'愛著', 'Bedenken':'顧慮',
    'heiraten':'結婚', 'glänzende':'光輝的',
    'erwarten':'期待', 'angesehenen':'有聲望的',
    'Partner':'伴侶', 'vorbestimmte':'命定的',
    'Werten':'價值觀', 'Schlechtes':'壞事',
    'rückblickend':'回想起來', 'schrecklich':'可怕地',
    'beengte':'束縛的', 'Lebensweise':'生活方式',
    'Bälle':'舞會', 'wach':'清醒',
    'hübschen':'漂亮的', 'Accessoire':'飾品',
    'herumtrug':'戴著', 'jenen':'那些',
    'allermeisten':'絕大多數', 'gespürt':'感受到了',
    'überraschte':'讓人驚訝', 'Nichts':'什麼都沒有',
    'gewöhnlich':'普通', 'aussehender':'看起來的',
    'dunklem':'深色的', 'erschienen':'出現了',
    'sehe':'看到', 'Entschuldigt':'抱歉',
    'Verspätung':'遲到了', 'gebt':'給我',
    'jederzeit':'隨時', 'blockierter':'被封鎖的',
    'üblich':'通常', 'befindet':'在',
    'Beste':'最好的', 'nutzlos':'沒用的',
    'Hälfte':'一半', 'reduziert':'降低了',
    'Kommando':'指揮', 'Truppen':'部隊',
    'sagt':'說', 'anhalten':'停下',
    'gedulden':'耐心等', 'scheinen':'似乎',
    'Forderungen':'要求', 'gestellt':'提出了',
    'zusammenarbeiten':'合作', 'abwarten':'等待',
    'warte':'等一下', 'Mithrilpinzette':'秘銀鑷子',
    'gemahlenes':'磨碎的', 'Drachenknochenpulver':'龍骨粉',
    'aschfarbenen':'灰色的', 'zählte':'數著',
    'Geräte':'器具', 'Zutaten':'材料',
    'Schrank':'櫃子', 'Hilfe':'幫忙',
    'wert':'值得', 'Darf':'可以嗎',
    'wofür':'用來做什麼', 'auskannte':'精通',
    'modifizierte':'改造了', 'Modifikation':'改造',
    'Artefaktes':'文物的', 'vorübergehend':'暫時地',
    'Unglaublich':'不可思議', 'Lösungsweg':'解法',
    'parat':'準備好了', 'mächtiges':'強大的',
    'benötigte':'需要的', 'ungeheuer':'極其',
    'müssten':'必須', 'hierzu':'為此',
    'zusammentun':'合力', 'unermesslichen':'無可估量的',
    'Intellekt':'智慧', 'zuzuschlagen':'出手',
    'freu':'期待', 'ehemaligen':'前',
    'Puls':'脈搏', 'normal':'正常',
    'Unregelmäßigkeiten':'異常', 'definitiv':'肯定的',
    'Glückstag':'幸運日', 'dünne':'細細的',
    'Schnittwunde':'切傷', 'Bin':'我是',
    'vollen':'全部的', 'zurückkommen':'回來',
    'währenddessen':'與此同時', 'lesen':'讀',
    'verbrachten':'度過了', 'hineinschien':'照進來',
    'verblasste':'褪去了', 'färbte':'染成了',
    'purpurrot':'紫紅色', 'Toilette':'廁所',
    'weshalb':'為什麼', 'Magenmittel':'胃藥',
    'verwirrter':'更困惑的', 'annahm':'以為',
    'tiefschwarz':'漆黑', 'stockfinster':'伸手不見五指',
    'hereingebrochen':'降臨了', 'Schneidersitz':'盤腿',
    'las':'讀著', 'Beeindruckend':'真厲害',
    'aufgeregt':'興奮地', 'getimt':'掐好了時間',
    'liegt':'在於', 'L-ich':'我、我',
    'geb':'給', 'Kellertreppe':'地下室樓梯',
    'gesenkten':'低著的', 'Hauptes':'頭',
    'unterirdischen':'地下的', 'erhellt':'照亮了',
    'verschlungen':'曲折的', 'falschen':'錯誤的',
    'Kurve':'彎道', 'herausfinden':'找出來',
    'Weges':'路的', 'Geradeaus':'直走',
    'zögernd':'猶豫地', 'unterirdische':'地下的',
    'angefleht':'哀求過', 'kostbare':'珍貴的',
    'Erinnerung':'記憶', 'leiblichen':'親生的',
    'Geburt':'出生', 'verblassten':'模糊了',
    'neuntem':'九歲的', 'Geburtstag':'生日',
    'Einbrecher':'入侵者', 'Spalt':'縫隙',
    'Kleiderschrank':'衣櫃', 'versteckt':'躲著',
    'Schreie':'尖叫聲', 'grässliche':'可怕的',
    'Schattens':'影子的', 'verfolgten':'追著',
    'Träumen':'夢境', 'Wort':'話語',
    'isolierte':'封閉了', 'besessen':'被詛咒的',
    'Fußstapfen':'腳步', 'treten':'踏上',
    'rettete':'拯救了', 'unterstützte':'支持了',
    'schenkte':'給了', 'Geborgenheit':'安全感',
    'wiederfand':'重新找到了', 'verbunden':'連結著',
    'revanchieren':'報答', 'schritt':'走入了',
    'Furcht':'恐懼', 'erreichte':'到達了',
    'verzweigte':'分叉了', 'Einer':'一條',
    'Erdgeschoss':'一樓', 'geradeaus':'直走',
    'verglich':'對照著', 'wonach':'要找什麼',
    'suchte':'找著', 'kleiner':'小的',
    'verband':'通往', 'hineinpassen':'鑽進去',
    'hinein':'進去', 'entspannen':'放鬆',
    'saßen':'坐著', 'Lehrer':'老師',
    'vorbereiteten':'準備好的', 'entwichen':'逃出了',
    'schwebende':'飄浮的', 'leuchtenden':'發光的',
    'zögern':'猶豫', 'Schacht':'管道',
}

TARGET = 'page8.html'

with open(TARGET, 'r', encoding='utf-8') as f:
    html = f.read()

def repl(m):
    w = m.group(1)
    if w in M:
        return f'<span class="d">{w}<span class="t">{M[w]}</span></span>'
    return m.group(0)

html = re.sub(r'<span class="d">([^<]+)<span class="t">（德）</span></span>', repl, html)

d = len(re.findall(r'<span class="d">', html))
c = len(re.findall(r'<span class="c">', html))
u = len(re.findall(r'（德）', html))

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✅ 完成  d={d} c={c} 佔比={d/(d+c)*100:.1f}% 未翻譯={u}')
