# -*- coding: utf-8 -*-
import re, collections

FINAL_MAP = {
    'Seine':'他的', 'richtige':'正確的', 'Jawohl':'遵命', 'sowieso':'反正',
    'schienen':'似乎', 'länger':'更長', 'Schnell':'快', 'bleiben':'永遠',
    'drehten':'轉過身', 'sieht':'看起來', 'sonst':'否則', 'ihres':'她的',
    'mach':'做', 'Landes':'國家的', 'still':'安靜', 'trug':'穿著',
    'Denk':'想想', 'meinst':'你是說', 'nötig':'需要', 'Kapitel':'章',
    'vielen':'許多', 'gelaunt':'心情愉快', 'Seit':'自從', 'besuchte':'上了',
    'Da':'由於', 'Zahl':'人數', 'Bushin-Stils':'武神流的',
    'skandalösen':'醜聞的', 'Herrn':'先生', 'zurückgegangen':'減少了',
    'gehörten':'屬於了', 'umgebracht':'殺掉', 'geküsst':'親過',
    'führten':'進行著', 'Gespräche':'對話', 'fort':'下去',
    'absolute':'完全的', 'trainieren':'訓練', 'notwendig':'必要的',
    'Habt':'你們有', 'abschneide':'表現好', 'abschleppen':'追到',
    'aufreißen':'搭上', 'Hast':'你有', 'riesiges':'巨大的',
    'Jahre':'歲', 'stattfand':'舉辦', 'nah':'近處', 'fern':'遠方',
    'kamen':'來了', 'weltweit':'全世界', 'stärksten':'最強的',
    'extra':'特別', 'reserviert':'預留的', 'entscheiden':'決定',
    'gewöhnlicher':'普通的', 'wichtigen':'重要的', 'ungewollte':'不必要的',
    'ziehen':'引來', 'bedanken':'感謝', 'beenden':'說完',
    'L-Lu':'魯', 'Niemand':'沒有人', 'tust':'裝得',
    'rechter':'右', 'lockerte':'鬆開了', 'spezifisch':'具體',
    'hilf':'幫一下', 'zufällig':'碰巧', 'begleiten':'陪著',
    'dahin':'那裡', 'aussehende':'看起來的', 'untersuchen':'調查',
    'meistens':'大多時候', 'informiert':'消息靈通',
    'Dort':'那裡', 'bildeten':'構成了', 'eher':'比較',
    'Lehre':'教學', 'Schwerpunkt':'重點', 'Hmmm':'嗯',
    'Stimmt':'對了', 'irgendwie':'好像', 'Unsere':'我們的',
    'Blicke':'目光', 'trafen':'對上了', 'verärgert':'惱怒地',
    'Wut':'憤怒', 'geworden':'變成了', 'Solang':'只要',
    'raushielt':'遠離', 'rumrennen':'到處跑',
    'abschlachten':'屠殺', 'verbessert':'進步了',
    'schaden':'壞事', 'lebendige':'活的',
    "sie's":'她', 'absieht':'盯上',
    'diskutierte':'討論著', 'gewisse':'某件',
    'intelligentesten':'最聰明的', 'Personen':'人物',
    'Königreich':'王國', 'bekannt':'聞名',
    'entziffern':'解讀', 'rothaarige':'紅髮的',
    'aussah':'看起來像', 'hübsches':'漂亮的',
    'rosa':'粉紅色的', 'Augenschein':'端詳',
    'national':'國內', 'international':'國際',
    'gefeiert':'受到讚揚', 'Kein':'沒有',
    'aufnehmen':'相比', 'A-Aber':'可、可是',
    'abzulehnen':'推辭', 'mischte':'插了',
    'annehmen':'接受', 'Herr':'先生',
    'Vize-Schulleiter':'副校長', 'Vater':'父親',
    'leichtes':'些許的', 'Ausdruck':'表情',
    'brachte':'表達了', 'weltberühmte':'舉世聞名的',
    'nachzugehen':'去做', 'schillernde':'光輝的',
    'bescheren':'帶來', 'oft':'多少次',
    'bewältigen':'完成', 'legte':'放了',
    'Sherrys':'雪莉的', 'schmale':'纖細的',
    'Okay':'好吧', 'entgegen':'接過來',
    'religiösen':'宗教的', 'sogenannten':'所謂的',
    'Angehörigen':'成員們', 'untersucht':'研究了',
    'großem':'極大的', 'Interesse':'興趣',
    'reagierte':'反應道', 'ehrlich':'坦白',
    'zurückholen':'奪回', 'äußerst':'極其',
    'beunruhigend':'令人不安', 'schmaler':'瞇了起來',
    'beschlagnahmt':'沒收了', 'leider':'可惜',
    'aufbewahrten':'存放的', 'Kurzem':'不久前',
    'niedergebrannt':'燒毀了', 'Übrig':'剩下',
    'geblieben':'的', 'einzig':'唯一',
    'neulich':'前幾天', 'entsinne':'記得',
    'bestehenden':'現有的', 'unveränderter':'不變的',
    'erlauben':'允許', 'sinnvollsten':'最合理的',
    'unentschlossen':'猶豫不決', 'ganze':'整個',
    'müsst':'必須', 'erheblich':'大大地',
    'verzögern':'延誤', 'durchtrainierten':'精壯的',
    'zierte':'點綴著', 'überlassen':'交給',
    'lass':'讓', 'Je':'越', 'weniger':'少',
    'einteilt':'安排', 'umso':'越',
    'kümmern':'處理', 'schwieg':'沉默了',
    'unterbesetzt':'人手不足', 'kenne':'認識',
    'Einwände':'異議', 'Unterschied':'區別',
    'solange':'只要', 'meintest':'你說的',
    'Ähnliches':'類似的話', 'siegreichen':'得意的',
    'Grinsen':'笑容', 'Dabei':'以前',
    'artig':'乖巧', 'eingeschnappt':'不高興地',
    'vorhaben':'打算做什麼', 'gefährlich':'危險的',
    'Schulleistungen':'學業成績', 'beeinträchtigt':'影響',
    'ungefährlich':'安全', 'möglich':'可能',
    'Viel':'祝你', 'Glück':'好運',
    'abzumelden':'退出報名', 'verließ':'離開了',
    "Hat's":'結果', 'geklappt':'成了嗎',
    'fragten':'問道', 'warteten':'等著',
    'gewinnst':'贏了', 'gewinnt':'贏',
    'schüttelte':'搖了搖', 'Mir':'我',
    'zeige':'帶你看', 'aufheitern':'開心一下',
    'S-So':'那、那種', 'stotterte':'結巴地說',
    'atmete':'吸了', 'scharf':'一口氣',
    'verkaufen':'賣', 'irgend':'某個',
    'Klingt':'聽起來', 'lecker':'好吃',
    'sollst':'應該', 'A-Ach':'啊、原來',
    'echter':'真正的', 'Lass':'讓我們',
    "geht's":'走吧', 'interessierte':'感興趣',
    'emporragendes':'高聳的', 'Luxusgebäude':'豪華建築',
    'geschmackvollen':'有品味的', 'modernen':'現代的',
    'beschlich':'產生了', 'fehl':'格格不入',
    'Platz':'地方', 'versehentlich':'不小心',
    'erstklassiges':'高級的', 'Markengeschäft':'精品店',
    'reingestolpert':'走進去', 'Eingang':'入口',
    'ellenlange':'超長的', 'ausschließlich':'清一色',
    'Aristokraten':'貴族', 'Klientel':'客層',
    'Wartezeit':'等候時間', 'beträgt':'為',
    'achtzig':'八十', 'anstellen':'排隊',
    'versetzte':'說道', 'Gerüchte':'傳聞',
    'umgeht':'出沒', 'aufpassen':'小心',
    'folgten':'跟著', 'O-Okay':'好、好的',
    'erklärte':'解釋道', 'Una':'嗯',
    'suchen':'找', 'H-H-Hey':'嗨、嗨',
    'D-Du':'你、你', 'H-H-Hast':'你、你有',
    'irgendwelche':'什麼', 'danach':'之後',
    'werter':'尊貴的', 'dauern':'花',
    'auszufüllen':'填寫', 'I-l-Ich':'我、我也',
    'fülle':'填', 'I-Ich':'我、我',
    'Baten':'懇求著', 'flehentlich':'苦苦地',
    'geführt':'帶到', 'diverse':'各種',
    'Sogar':'甚至', 'naher':'不久的',
    'Angestelltentür':'員工通道', 'kennt':'知道的',
    'Über':'通過', 'gelangten':'來到了',
    'Davor':'在那前面', 'verbeugten':'鞠了躬',
    'Vor':'在我面前', 'Den':'那條',
    'Saals':'大廳的', 'komme':'來的',
    'Fragebogens':'問卷的', 'Raumes':'房間的',
    'Neben':'旁邊', 'gewartet':'等候',
    'dritte':'第三', 'Unter':'在其中',
    'super':'超級', 'schlag':'打',
    'Mehr':'更多', 'Stil':'風格',
    'Ahhh':'啊啊啊', 'Stolperte':'絆倒了',
    'rein':'完全', 'D-Diese':'這、這些',
    'schob':'推給了', 'aufstand':'站起來',
    'okay':'沒關係', 'Deine':'你的',
    'B-Bitte':'請、請', 'geschafft':'做到了',
    'prächtige':'壯觀的', 'zutiefst':'深深地',
    'hinauf':'上方', 'knienden':'跪著的',
    'Besonderes':'特別的', 'half':'幫助',
    'kleinere':'較小的', 'zitterten':'顫抖著',
    'Gute':'做得好', 'Gebäudes':'建築的',
    'Trotz':'儘管', 'versteh':'懂了',
    'indem':'通過', 'lässt':'讓',
    'konntest':'你怎麼能', 'Tja':'算了',
    "soll's":'就這樣吧', "ich's":'我懂了',
    'Mich':'我', 'allen':'所有',
    'In-':'國內', 'wichtigsten':'最重要的',
    'Hätten':'要是', 'jeden':'每',
    'r':'', 'Verzeiht':'請原諒',
    'Haufen':'堆裡', 'befanden':'藏著',
    'gesteckt':'塞進了', 'jemandem':'任何人',
    'S-Seid':'您、您', 'zufrieden':'滿意',
    'geliehen':'借了', 'genommen':'拿了',
    'lege':'放回', 'schoben':'推走了',
    'höre':'聽到', 'versunken':'沉思著',
    'unruhig':'不安地', 'rollte':'滑落了',
    'einzelne':'一滴', 'herunter':'下來',
    'Anblick':'看到', 'Ohne':'沒有',
    'Nicken':'點頭', 'Welcher':'哪個',
    'Jungen':'少年', 'blauvioletten':'藍紫色的',
    'heilte':'治癒了', 'Wichtiges':'重要的東西',
    'wahres':'真正的', 'unglaubliche':'難以置信的',
    'jemals':'曾經', 'überhaupt':'到底',
    'arbeitete':'繼續工作', 'hinterließ':'留下了',
    'kleinsten':'最小的', 'sämtlichen':'所有的',
    'finden':'找到', 'nimmer':'絕不',
    'Oho':'哦喔', 'kurzer':'短暫的',
    'eigenem':'自己的', 'Verstanden':'明白了',
    'kaufen':'買', 'Hundert':'一百',
    'Kagenou':'影野', 'Antworten':'回答',
    'wahlloser':'隨機的', 'sagten':'說道',
    'gleichzeitig':'同時地', 'Schwertern':'劍',
    'statt':'發生著', 'Komm':'快點',
    'fängt':'開始了', 'gleich':'馬上',
    'aufs':'去', 'würden':'會',
    'Geht':'快走', 'machst':'做的事',
    'Freunde':'朋友', 'Los':'走',
    'gegeneinander':'互相', 'Anhand':'根據',
    'erledige':'解決', 'geschieht':'會發生',
    'Lasst':'讓', 'Irgendwas':'有什麼',
    'tragen':'穿', 'Um':'為了',
    'gelegenes':'附近的', 'genauer':'仔細地',
    'Gib':'放棄吧', 'verlief':'進行著',
    'Warum':'為什麼', 'euer':'你們的',
    'Hat':'是', 'tat':'做的',
    'dahinter':'背後', 'demselben':'相同的',
    'richtigen':'正確的', 'dritten':'第三方',
    'zusehen':'看著', 'zusah':'看著',
    'Zunge':'舌頭', 'wollt':'想要',
    'antreten':'對抗', 'dreimal':'三次',
    'Guckt':'看', 'Immer':'不停地',
    'änderte':'改變了', 'Wollt':'你們想',
    'gucken':'看看', 'Wäre':'會更',
    'Aghh':'啊', 'rechtzeitig':'及時',
    'Trick':'計策', 'ehe':'在……之前',
    'zweiten':'第二', 'Gegners':'對手的',
    'Situation':'局勢', 'hingegen':'相反',
    'mindestens':'至少', 'heimlich':'偷偷地',
    'eingesteckt':'藏起來的', 'gern':'喜歡',
    'gewonnen':'贏得', 'je':'曾經',
    'Schwertes':'劍術的', 'werdet':'將要',
    'eurem':'你們的', 'Kaum':'剛',
    'Ihre':'他們的', 'Wände':'牆壁',
    'einfaches':'輕鬆的', 'W-Warte':'等、等等',
    'gewollt':'願意的', 'Wofür':'為了什麼',
    'wen':'誰', 'kämpfst':'戰鬥',
    'Wesens':'生物', 'Instinkten':'本能',
    'würdest':'你會', 'Wirst':'你會',
    'H-ris':'姊、姊姊', 'H-Hier':'這、這裡',
    'drüben':'這邊', 'Kurz':'就在',
    'bevor':'在……之前', 'fing':'接住了',
    'alleine':'獨自', 'später':'之後',
    'lagen':'散落著', 'Hris':'姊姊',
    'Glaub':'相信', 'tiefes':'深深的',
    'enge':'狹窄的', 'gehabt':'有過',
    'zurückweichen':'退縮', 'Vom':'從',
    'Irgendeine':'某個', 'schwarze':'黑色的',
    'Schwerter':'劍', 'machten':'做了',
    'passierte':'發生了', 'Ahh':'啊',
    'tiefen':'深沉的', 'W-Was':'什、什麼',
    'Erfüllt':'充滿了', 'zweite':'第二個',
    'dachtest':'你以為', 'könntest':'你能',
    'W-Wie':'怎、怎麼', 'Hinter':'在背後',
    'Bist':'是', 'unterhielten':'交談著',
    'hinweg':'頭上', 'panisch':'驚恐地',
    'drückte':'按著', 'Damit':'說完',
    'wartete':'等著', 'voll':'全副',
    'Aaaaahhhhh':'啊啊啊啊', 'aufzuheben':'撿起',
    'Gagh':'咕嘎', 'kalte':'冰冷的',
    'dahintersteckt':'幕後黑手', 'hieß':'叫做',
    'Alles':'一切', 'Könnten':'他們會不會',
    'irgendeine':'某個', 'Ganze':'一切',
    'vorerst':'暫時', 'Entweder':'要嘛',
    'Beide':'兩者都', 'darfst':'你不能',
    'Diesbezüglich':'關於此', 'orden':'騎士團',
    'dazugeben':'補貼', 'Angebot':'提議',
    'Weißt':'你知道', 'Acht':'八',
    'Richtig':'沒錯', 'ganzes':'整整',
    'unterstützen':'維持', 'rekrutieren':'招募',
    'steht':'站在', 'fiele':'很難',
    'auszusprechen':'說出口', 'rückte':'湊近了',
    'näher':'更近', 'Mensch':'人類',
    'tagelang':'好幾天', 'gegeben':'給了',
    'übers':'撫摸了', 'Ruh':'好好',
    'werd':'趕快', 'Erste':'暫時',
}

with open('page6.html', 'r', encoding='utf-8') as f:
    html = f.read()

def replace_unknown(m):
    word = m.group(1)
    if word in FINAL_MAP:
        zh = FINAL_MAP[word]
        if zh:
            return f'<span class="d">{word}<span class="t">{zh}</span></span>'
    return m.group(0)

html = re.sub(
    r'<span class="d">([^<]+)<span class="t">（德）</span></span>',
    replace_unknown,
    html
)

d_count = len(re.findall(r'<span class="d">', html))
c_count = len(re.findall(r'<span class="c">', html))
unknown = len(re.findall(r'（德）', html))

with open('page6.html', 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✅ 最終翻譯修補完成')
print(f'   德文詞 (.d): {d_count}')
print(f'   中文互動詞 (.c): {c_count}')
if d_count + c_count > 0:
    print(f'   德文佔比: {d_count/(d_count+c_count)*100:.1f}%')
print(f'   仍需手動翻譯: {unknown}')
