# -*- coding: utf-8 -*-
import re, collections

NEW_MAP = {
    # 人名
    'Rose': '蘿絲', 'Roses': '蘿絲的', 'Oriana': '奧莉安娜',
    'Laugus': '勞古斯', 'Kagenou': '影野', 'Lukreia': '露克蕾雅',
    'Rex': '雷克斯', 'Kars': '卡爾的',

    # 地點/組織
    'Magieritterakademie': '魔法騎士學院', 'Bibliothek': '圖書館',
    'Park': '公園', 'Arena': '競技場', 'Labor': '研究室',
    'Klassenzimmer': '教室', 'Forschungszimmer': '研究室',
    'Schule': '學校', 'Klasse': '班級',
    'Gelehrtenakademie-Schülerin': '學者學院的女學生',
    'Oberstufe': '高年級',

    # 家庭
    'Vater': '父親', 'Mutter': '母親', 'Tochter': '女兒',
    'Kinder': '孩子們', 'Kindern': '孩子們', 'Kind': '孩子',
    'Stiefvater': '繼父', 'Verlobte': '未婚妻', 'Verlobten': '未婚夫',
    'Freunde': '朋友們', 'Freundschaften': '友情',
    'Familie': '家庭', 'Dame': '女士',
    'Jungen': '少年們', 'Mädchens': '女孩的',

    # 物品/食物
    'Tasse': '杯子', 'Tassen': '杯子',
    'Tee': '茶', 'Kekse': '餅乾', 'Eis': '冰淇淋',
    'Milch': '牛奶', 'Packung': '包裝', 'Schokolade': '巧克力',
    'Schachtel': '盒子', 'Fussel': '毛球',
    'Brille': '眼鏡', 'Schnurrbart': '鬍子',
    'Schuluniform': '校服', 'Hose': '褲子',
    'Sofa': '沙發', 'Bank': '長椅',
    'Geschenk': '禮物',

    # 動詞
    'stellte': '裝出', 'reden': '說話', 'denken': '想',
    'denke': '認為', 'denk': '想',
    'lächelte': '微笑了', 'flüsterte': '低語著',
    'öffnete': '打開了', 'streckte': '伸出了',
    'plauderten': '聊著天', 'dachten': '以為',
    'vorstellen': '想像', 'bedeutete': '意味著',
    'reagieren': '反應', 'bewegte': '動了',
    'riss': '撕裂了', 'klirrte': '叮噹響了',
    'lachen': '笑', 'lachte': '笑了',
    'erklären': '解釋', 'erinnern': '記得',
    'starrte': '盯著', 'merkte': '注意到了',
    'breitete': '展開了', 'streichelte': '撫摸了',
    'rieb': '揉著', 'kramte': '翻找著',
    'packte': '抓住了', 'klammerte': '緊握著',
    'erwähnte': '提到了', 'hakte': '追問道',
    'hinhielt': '遞過去', 'schlenderten': '漫步著',
    'konzentrieren': '集中精神',
    'verändern': '改變', 'studieren': '學習',
    'bewachen': '看守', 'berichten': '報告',
    'verhört': '審問了', 'verließen': '離開了',
    'herauszulocken': '引誘出來', 'entlocken': '套出',
    'fortsetzen': '繼續', 'erstatten': '報告',
    'erfahren': '得知', 'existierte': '存在著',
    'belästigt': '騷擾', 'genossen': '享受著',
    'geübt': '練習了', 'arbeitest': '工作',
    'aussehen': '看起來', 'berühren': '觸碰',
    'adoptiert': '收養了', 'gestorben': '去世了',
    'probier': '試試',
    'geopfert': '犧牲了', 'gebrochen': '打破了',
    'galten': '被認為', 'zeigten': '表現出',
    'unterzogen': '接受了', 'verabreichte': '給予了',
    'bestätigt': '確認了', 'gesichtet': '發現了',
    'geleistet': '做出了', 'erhielten': '獲得了',
    'aufstiegen': '晉升了', 'aufgenommen': '接納了',
    'unterließ': '省略了', 'führt': '導致',
    'ausgehen': '推斷',
    'erpressen': '勒索', 'streuen': '散布',
    'verpassen': '給以', 'verfärbten': '染成了',
    'träumen': '做夢', 'geleiten': '護送',
    'erklomm': '攀上了', 'lautete': '是',
    'geschah': '發生了', 'schmeckt': '好喝',
    'wohnte': '住在', 'angefreundet': '成為了朋友',
    'beobachtet': '觀察', 'angestarrt': '盯著看',
    'tuschelten': '竊竊私語', 'niederschlugen': '垂下了',
    'trugen': '穿著', 'stieß': '發出了',
    'zuschlagen': '出手', 'bieten': '提供',
    'taten': '假裝', 'bemerkten': '注意到了',
    'wandten': '轉過了', 'vernahmen': '聽到了',
    'teilten': '分成了', 'nutzten': '利用了',
    'gaben': '給了',
    'vorbeikam': '路過', 'verwirrte': '困惑了',
    'verwirrten': '困惑的',
    'gefüllt': '裝滿了', 'roch': '聞起來',
    'versprochen': '答應了', 'bekommt': '收到',
    'ergattern': '搶到', 'antworten': '回答',
    'wartet': '等著', 'lernen': '學習',
    'brauchen': '需要', 'angefangen': '開始了',
    'ähnelt': '相似',
    'hingeben': '沉浸', 'geforscht': '研究了',
    'angenommen': '接受了',
    'hingetan': '放到哪裡了',
    'weiterentwickeln': '更進一步',
    'zurücklassen': '留下', 'beschienen': '照耀著',
    'auszugeben': '花掉',
    'übertraf': '超越了',
    'handelt': '是', 'gelitten': '受苦了',
    'glauben': '相信', 'spazierten': '散步著',
    'weiterkämpfen': '繼續戰鬥', 'klammern': '抓緊',
    'erinnerten': '讓人想起', 'ausstreckte': '伸出了',
    'herausfindet': '查出來', 'eingedrungen': '入侵了',
    'schminkst': '化妝', 'lasse': '讓',
    'ruiniert': '毀了',
    'erwartet': '預料', 'erwartete': '期待著',
    'freut': '高興',
    'verletzt': '受傷的',

    # 形容詞
    'nervös': '緊張的', 'süß': '甜的',
    'friedliche': '和平的', 'friedlichen': '和平的',
    'knapp': '簡短地', 'feucht': '濕潤的', 'feuchten': '濕潤的',
    'dünn': '纖細的', 'dünnem': '薄薄的',
    'schmales': '瘦削的', 'schmale': '纖細的',
    'sanft': '溫柔地', 'blass': '蒼白的',
    'süßlich': '甜甜的', 'graue': '灰色的',
    'teure': '昂貴的', 'hochwertige': '高級的',
    'geröteten': '泛紅的', 'unverwechselbar': '獨特的',
    'brillante': '出色的', 'verlegen': '不好意思地',
    'leichten': '輕微的',
    'kranken': '生病的', 'wenige': '少數的', 'wenigen': '少數的',
    'komische': '奇怪的', 'wahre': '真正的',
    'glühenden': '熾熱的',
    'reif': '成熟的', 'charmant': '有魅力的',
    'naives': '天真的', 'menschenleer': '空無一人的',
    'normale': '正常的', 'reibungslose': '順利的',
    'bloße': '僅僅的', 'selbstverständlich': '理所當然的',
    'absurde': '荒謬的', 'stärkste': '最強的',
    'perfekt': '完美的', 'speziellen': '特殊的',
    'spezifischen': '特定的', 'einfachen': '簡單的',
    'feurigen': '炙熱的', 'unbeugsamen': '不屈的',
    'mächtigen': '強大的',
    'fester': '更緊地', 'verschwitzten': '汗濕的',
    'gleichgesinnte': '志同道合的',
    'glanzvolles': '輝煌的', 'damaligen': '當時的',
    'muskulöse': '肌肉發達的', 'steifes': '僵硬的',
    'frischer': '清新的', 'erfrischender': '令人振奮的',
    'gekämmte': '整齊梳理的',
    'hochgestecktes': '盤起的',
    'persönlich': '親自', 'aufrecht': '挺直地',
    'männliche': '男性', 'sozialen': '社交的',
    'bestimmten': '特定的', 'besonderen': '特別的',
    'seltener': '更稀少', 'vorsichtig': '小心地',
    'rotorange': '橘紅色',
    'namhaftes': '著名的', 'namhaften': '著名的',
    'jahrelangen': '多年的',
    'strengen': '嚴格的', 'regelmäßig': '定期地',

    # 名詞
    'Nebencharakters': '配角的',
    'Wangen': '臉頰', 'Sorgen': '擔心',
    'Einrichtungen': '設施', 'Runde': '回合',
    'Künste': '技藝', 'Jubel': '歡呼',
    'Champion': '冠軍', 'Problem': '問題',
    'Arzt': '醫生', 'Verletzungen': '傷勢',
    'Mittagspause': '午休', 'Auftrag': '任務',
    'Rittern': '騎士們', 'Ordnung': '規矩',
    'Forschungen': '研究', 'Hause': '家',
    'Zimmer': '房間', 'Make-up': '化妝',
    'Gerücht': '傳聞', 'Geschichte': '歷史',
    'Gott': '天啊', 'Dritten': '第三名',
    'Zweiten': '第二名', 'Ersten': '第一名',
    'Gehirnwäsche': '洗腦', 'All': '所有的',
    'Publikum': '觀眾', 'Kampfgeist': '鬥志',
    'Grenzen': '極限', 'Willen': '意志',
    'Schluck': '一口', 'Klopf': '咚咚',
    'Alltag': '日常', 'Seufzer': '嘆息',
    'Gang': '走廊', 'Entfernung': '距離',
    'Hilferufe': '求救聲', 'Intelligenzbestien': '聰明人',
    'Ort': '地方', 'Essensvorlieben': '飲食喜好',
    'Zimmernummer': '房間號碼', 'Toiletten': '廁所',
    'Schuhgröße': '鞋碼', 'Parfums': '香水',
    'Farben': '顏色', 'Größen': '尺寸',
    'Ergebnis': '結果', 'Stalker': '跟蹤狂',
    'Gegend': '地方', 'Objekten': '物品',
    'Damenwelt': '女性', 'Liebe': '愛情',
    'Mühe': '努力', 'Fähigkeit': '能力',
    'Chiffren': '密碼', 'Erinnerungen': '回憶',
    'Forscherblick': '研究者的眼光',
    'Hustenanfall': '咳嗽', 'Krankheiten': '疾病',
    'Einladung': '邀請', 'Akademische': '學術的',
    'Köpfe': '人才', 'Dutt': '丸子頭',
    'Farbe': '顏色', 'Erfahrung': '經驗',
    'Haarschnitt': '髮型', 'Lady': '淑女',
    'Illusion': '幻覺', 'Frieden': '和平',
    'Turm': '塔', 'Mischung': '混合',
    'Neid': '嫉妒', 'Mitleid': '同情',
    'Gesichter': '面孔', 'Besessenheit': '執念',
    'Hoffnungsschimmer': '一絲希望',
    'Ecke': '角落', 'Titelseite': '頭版',
    'Meister': '大師', 'Existenzen': '存在',
    'Marquis': '侯爵', 'Bekanntenkreis': '社交圈',
    'Zeiten': '時代', 'Aussehen': '外表',
    'Schminken': '化妝', 'Versager': '廢物',
    'Bauern': '棋子', 'Schachbrett': '棋盤',
    'Vorfällen': '事件', 'Merkmalen': '特徵',
    'Waisen': '孤兒', 'Begabung': '天賦',
    'Ausbildung': '訓練', 'Folge': '結果',
    'Beitrag': '貢獻', 'Schilde': '盾牌',
    'Ermittlungen': '調查', 'Neues': '新的',
    'Horizont': '地平線', 'Hosenscheißer': '膽小鬼',
    'Stimmung': '氣氛', 'Abschaum': '人渣',
    'Umfeld': '環境', 'Tracht': '一頓',
    'Prügel': '揍', 'Wolken': '雲',
    'Nacken': '脖子', 'Pärchen': '情侶',
    'Schulleben': '校園生活', 'Vorstellung': '想法',
    'Abschluss': '畢業', 'Spitze': '頂端',
    'Weise': '方式', 'Austauschschülerin': '交換生',
    'Besessenen': '被詛咒者', 'Ausgestoßenen': '被放逐者',

    # 副詞/虛詞
    'Kann':'能', 'Klar':'當然', 'oft':'常常',
    'Eigentlich':'其實', 'vorbei':'過去了',
    'übrig':'剩下的', 'Aha':'原來如此',
    'beim':'在', 'größten':'最大的',
    'Natürlich':'當然', 'verwendet':'使用',
    'geh':'去吧', 'schief':'出錯',
    'heißt':'叫做', 'geschenkt':'送的',
    'Willst':'你想', 'willst':'想要',
    'weit':'遠', 'musst':'你必須',
    'J-Ja':'是、是的', 'Oh':'哦',
    'überrascht':'驚訝的', 'Ganz':'完全',
    'weiteren':'更多的', 'Irgendwie':'總覺得',
    'War':'是嗎', 'abgestumpft':'麻木了',
    'erleichtert':'鬆了一口氣', 'dreiunddreißig':'三十三',
    'Unmittelbar':'緊接著', 'längst':'早已',
    'besonders':'特別', 'froh':'開心',
    'heraus':'出來', 'zusammen':'一起',
    'gemeinsam':'一起', 'allein':'獨自',
    'Da':'那邊', 'wegen':'因為',
    'Erste':'首先', 'Ersten':'第一名',
    'tat':'做的', 'Jahr':'年',
    'Seine':'他的', 'Jawohl':'遵命',
    'sowieso':'反正', 'schienen':'似乎',
    'länger':'更長', 'Schnell':'快',
    'bleiben':'留下', 'drehten':'轉身了',
    'sieht':'看起來', 'sonst':'否則',
    'ihres':'她的', 'mach':'做',
    'Landes':'國家的', 'still':'安靜',
    'trug':'穿著', 'Denk':'想想',
    'meinst':'你是說', 'Meinst':'你是說',
    'nötig':'需要',
    'Alle':'所有人', 'Guck':'看',
    'ertappt':'被抓到了', 'Tat':'行為',
    'H-Hey':'嘿', 'G-Guten':'早、早安',
    'anstrengend':'累人的', 'anstrengender':'更累人的',
    'Guten':'早安',
    'Hehe':'嘿嘿', 'Zuerst':'首先',
    'Beispiel':'例子', 'einiger':'一些的',
    'älteres':'年長的', 'Gehen':'走吧',
    'abgesehen':'除了',
    'geistesabwesend':'心不在焉地',
    'irgendwo':'某處', 'hübsche':'漂亮的',
    'zweit':'兩個人', 'bestürzt':'震驚的',
    'Oha':'啊', 'Bestimmt':'肯定',
    'morgens':'早上', 'abends':'晚上',
    'voran':'前進', 'Unverwechselbar':'獨一無二',
    'geübtem':'訓練有素的',
    'Brauchst':'你需要', 'A-Alles':'沒、沒事',
    'Schon':'已經', 'Mach':'做',
    'schlauesten':'最聰明的', 'würdigen':'看一眼',
    'gehst':'你去', 'derselben':'同樣的',
    'sowie':'以及', 'Können':'能力',
    'Hättest':'你要是', 'deiner':'你的',
    'Lecker':'好好吃', 'wirkende':'看起來的',
    'dermaßen':'如此地', 'Gehst':'你去',
    'falle':'掉進', 'kannten':'認識',
    'mittlerweile':'如今', 'nahezu':'幾乎',
    'Normalerweise':'通常', 'zweifelte':'懷疑',
    'bevorstünde':'即將到來', 'lediglich':'只不過',
    'erbauter':'建造的', 'Einige':'有些人',
    'bliebe':'留下', 'jener':'那些',
    'daher':'因此', 'heutzutage':'如今',
    'Hmm':'嗯', 'erzähl':'告訴我',
    'tagsüber':'白天', 'Ohaaa':'哦哦哦',
    'älter':'更大', 'lebend':'活著',
    'A-Ach':'啊',
    'vielen':'許多',
    'meisten':'大多數', 'intakt':'完好的',
    'allerdings':'不過', 'außen':'外表',
    'einigen':'一些', 'armer':'可憐的',
    'einziges':'唯一的', 'Neulich':'最近',
    'alias':'化名', 'Verräterische':'背叛的',
    'derzeit':'目前', 'Solche':'這樣的',
    'jene':'那些', 'Jene':'那些',
    'beinahe':'幾乎', 'ehemaliges':'前',
    'gehörte':'屬於', 'erhalten':'得到',
    'sinnloserweise':'無意義地',
    'Mhm':'嗯', 'Irgendwo':'在某處',
    'kichernd':'笑著', 'soeben':'剛才',
    'jedenfalls':'無論如何',
    'vorletzten':'倒數第二',
    'AAAAAHHHHH':'啊啊啊啊啊',
    'Gelaunt':'心情好的', 'gelaunt':'心情好的',
    'Seit':'自從', 'besuchte':'上了',
    'Zahl':'數量',
    'Bushin-Stils':'武神流的',
    'skandalösen':'醜聞的',
    'Herrn':'先生',
    'zurückgegangen':'減少了',
    'i':'我',
}

with open('page6.html', 'r', encoding='utf-8') as f:
    html = f.read()

def replace_unknown(m):
    word = m.group(1)
    if word in NEW_MAP:
        zh = NEW_MAP[word]
        return f'<span class="d">{word}<span class="t">{zh}</span></span>'
    return m.group(0)

html = re.sub(
    r'<span class="d">([^<]+)<span class="t">（德）</span></span>',
    replace_unknown,
    html
)

d_count = len(re.findall(r'<span class="d">', html))
c_count = len(re.findall(r'<span class="c">', html))
unknown = len(re.findall(r'（德）', html))

with open('page6.html', 'w', encoding='utf-8') as f:
    f.write(html)

print(f'✅ 新詞翻譯完成')
print(f'   德文詞 (.d): {d_count}')
print(f'   中文互動詞 (.c): {c_count}')
if d_count + c_count > 0:
    print(f'   德文佔比: {d_count/(d_count+c_count)*100:.1f}%')
print(f'   仍需手動翻譯: {unknown}')

if unknown > 0:
    remaining = re.findall(r'<span class="d">([^<]+)<span class="t">（德）</span></span>', html)
    cc = collections.Counter(remaining)
    print(f'\n   剩餘 (前20)：')
    for w, cnt in cc.most_common(20):
        print(f'     {cnt:3d}  {w}')
